import type { ConstructionLibraryItemSeed, ConstructionLibraryCategory, ConstructionTrade } from "./vision-library.schema.js";

/**
 * Canonical Construction Library seed — "¿qué cosas conoce SEMSE?".
 * Spec: docs/specs/vision/sense-vision-field-library.spec.md §7.
 *
 * Single source of truth for the library rows. The versioned migration's
 * INSERT statements are generated from this file by
 * packages/db/scripts/generate-construction-library-sql.mjs, and
 * tests/unit/construction-library-seed.test.ts fails if they drift.
 *
 * Spanish names follow US-Hispanic job-site usage first (what a crew in the
 * US actually says), with Latin-American/Spain variants as aliases.
 */

type Names = [primary: string, ...aliases: string[]];

function item(
  slug: string,
  category: ConstructionLibraryCategory,
  subcategory: string,
  trades: ConstructionTrade[],
  en: Names,
  es: Names,
  text: {
    descEn: string;
    descEs: string;
    useEn: string;
    useEs: string;
    exEn: string;
    exEs: string;
    terms?: string[];
  },
): ConstructionLibraryItemSeed {
  const [nameEn, ...aliasesEn] = en;
  const [nameEs, ...aliasesEs] = es;
  return {
    slug,
    nameEn,
    nameEs,
    aliasesEn,
    aliasesEs,
    category,
    subcategory,
    trades,
    descriptionEn: text.descEn,
    descriptionEs: text.descEs,
    usageEn: text.useEn,
    usageEs: text.useEs,
    exampleSentenceEn: text.exEn,
    exampleSentenceEs: text.exEs,
    searchTerms: text.terms ?? [],
  };
}

const ELECTRICAL: ConstructionLibraryItemSeed[] = [
  item("emt-conduit", "electrical", "conduit", ["electrical"], ["EMT conduit", "EMT", "thin-wall conduit", "electrical metallic tubing", "pipe"], ["Tubo EMT", "conduit EMT", "tubería EMT", "tubo conduit"], {
    descEn: "Thin-wall galvanized steel tubing that protects and routes electrical wires.",
    descEs: "Tubo de acero galvanizado de pared delgada que protege y guía los cables eléctricos.",
    useEn: "Run branch circuits and feeders along walls and ceilings in commercial work.",
    useEs: "Se usa para llevar circuitos y alimentadores por paredes y techos en obra comercial.",
    exEn: "Grab four sticks of three-quarter EMT from the rack.",
    exEs: "Agarra cuatro tramos de EMT de tres cuartos del rack.",
    terms: ["conduit", "tubing"],
  }),
  item("emt-coupling", "fittings", "conduit-fitting", ["electrical"], ["EMT coupling", "set-screw coupling EMT", "conduit coupling"], ["Copla EMT", "cople EMT", "unión EMT", "acople EMT"], {
    descEn: "A fitting that joins two sections of EMT conduit end to end.",
    descEs: "Accesorio que une dos tramos de conduit EMT, uno a continuación del otro.",
    useEn: "Used to connect two sections of EMT conduit in a straight run.",
    useEs: "Se utiliza para unir dos tramos de EMT en una corrida recta.",
    exEn: "Bring me two three-quarter-inch EMT couplings.",
    exEs: "Tráeme dos coplas EMT de tres cuartos.",
    terms: ["coupling", "copla"],
  }),
  item("emt-connector", "fittings", "conduit-fitting", ["electrical"], ["EMT connector", "box connector", "conduit connector"], ["Conector EMT", "conector de caja", "conector para tubo EMT"], {
    descEn: "A fitting that attaches the end of EMT conduit to a box or panel, secured with a locknut.",
    descEs: "Accesorio que fija el extremo del EMT a una caja o panel, asegurado con contratuerca.",
    useEn: "Terminate EMT at a junction box, panel or enclosure knockout.",
    useEs: "Se usa para rematar el EMT en el knockout de una caja, panel o gabinete.",
    exEn: "We need a half-inch EMT connector for this box.",
    exEs: "Necesitamos un conector EMT de media para esta caja.",
    terms: ["connector", "conector"],
  }),
  item("compression-connector", "fittings", "conduit-fitting", ["electrical"], ["Compression connector", "EMT compression connector", "raintight connector"], ["Conector de compresión", "conector EMT de compresión"], {
    descEn: "An EMT connector that seals with a compression nut and ring instead of a set screw.",
    descEs: "Conector EMT que sella con tuerca y anillo de compresión en vez de tornillo.",
    useEn: "Terminate EMT where a tighter, raintight or damp-location connection is needed.",
    useEs: "Se usa para rematar EMT cuando se necesita una conexión más firme o a prueba de lluvia.",
    exEn: "Use compression connectors on the rooftop run, not set-screw.",
    exEs: "Usa conectores de compresión en la corrida del techo, no de tornillo.",
    terms: ["compression", "compresion"],
  }),
  item("compression-coupling", "fittings", "conduit-fitting", ["electrical"], ["Compression coupling", "EMT compression coupling", "raintight coupling"], ["Copla de compresión", "cople de compresión", "unión de compresión"], {
    descEn: "An EMT coupling tightened with compression nuts on both ends.",
    descEs: "Copla EMT que se aprieta con tuercas de compresión en ambos extremos.",
    useEn: "Join two EMT sections outdoors or in damp locations.",
    useEs: "Se usa para unir dos tramos de EMT en exteriores o lugares húmedos.",
    exEn: "Hand me a one-inch compression coupling.",
    exEs: "Pásame una copla de compresión de una pulgada.",
  }),
  item("set-screw-connector", "fittings", "conduit-fitting", ["electrical"], ["Set-screw connector", "set screw EMT connector", "screw-type connector"], ["Conector de tornillo", "conector EMT de tornillo"], {
    descEn: "An EMT connector held on the conduit by a tightening screw.",
    descEs: "Conector EMT que se sujeta al tubo apretando un tornillo.",
    useEn: "Terminate EMT at boxes in dry indoor locations quickly.",
    useEs: "Se usa para rematar EMT en cajas en interiores secos de forma rápida.",
    exEn: "Set-screw connectors are fine for the inside walls.",
    exEs: "Los conectores de tornillo sirven para las paredes interiores.",
    terms: ["set screw"],
  }),
  item("set-screw-coupling", "fittings", "conduit-fitting", ["electrical"], ["Set-screw coupling", "set screw EMT coupling"], ["Copla de tornillo", "cople de tornillo", "unión de tornillo"], {
    descEn: "An EMT coupling that grips each conduit end with set screws.",
    descEs: "Copla EMT que sujeta cada extremo del tubo con tornillos.",
    useEn: "Join EMT sections in dry indoor runs.",
    useEs: "Se usa para unir tramos de EMT en corridas interiores secas.",
    exEn: "Tighten both screws on every set-screw coupling.",
    exEs: "Aprieta los dos tornillos de cada copla de tornillo.",
  }),
  item("rigid-coupling", "fittings", "conduit-fitting", ["electrical"], ["Rigid coupling", "RMC coupling", "threaded coupling", "GRC coupling"], ["Copla rígida", "cople roscado", "unión rígida"], {
    descEn: "A threaded coupling for joining rigid metal conduit.",
    descEs: "Copla roscada para unir tubo conduit rígido de metal.",
    useEn: "Connect threaded rigid conduit sections, often outdoors or underground.",
    useEs: "Se usa para unir tramos de conduit rígido roscado, a menudo en exteriores o bajo tierra.",
    exEn: "Thread it and put a rigid coupling on the end.",
    exEs: "Hazle rosca y ponle una copla rígida al final.",
  }),
  item("locknut", "fittings", "conduit-fitting", ["electrical"], ["Locknut", "lock nut", "conduit locknut"], ["Contratuerca", "tuerca de seguridad"], {
    descEn: "A flat notched nut that secures a connector to a box from the inside.",
    descEs: "Tuerca plana dentada que asegura un conector a la caja por dentro.",
    useEn: "Lock connectors and fittings tight to a box or panel wall.",
    useEs: "Se usa para fijar conectores y accesorios a la pared de una caja o panel.",
    exEn: "Don't forget the locknut, and hit it with the screwdriver.",
    exEs: "No se te olvide la contratuerca, y dale con el desarmador.",
  }),
  item("bushing", "fittings", "conduit-fitting", ["electrical"], ["Bushing", "plastic bushing", "insulating bushing"], ["Boquilla", "bushing", "monitor"], {
    descEn: "A rounded ring threaded onto a conduit end to protect wire insulation.",
    descEs: "Anillo redondeado que se enrosca al final del tubo para proteger el aislamiento del cable.",
    useEn: "Prevent sharp conduit edges from cutting wires during pulls.",
    useEs: "Evita que los bordes filosos del tubo corten los cables al jalarlos.",
    exEn: "Put a bushing on that rigid before you pull.",
    exEs: "Ponle una boquilla a ese rígido antes de jalar.",
  }),
  item("grounding-bushing", "fittings", "conduit-fitting", ["electrical"], ["Grounding bushing", "ground bushing", "bonding bushing"], ["Boquilla de tierra", "boquilla con lengüeta de tierra"], {
    descEn: "A bushing with a lug for bonding the conduit to the grounding system.",
    descEs: "Boquilla con terminal para unir el tubo al sistema de tierra.",
    useEn: "Bond metal conduit at services and around concentric knockouts.",
    useEs: "Se usa para aterrizar el tubo metálico en acometidas y knockouts concéntricos.",
    exEn: "The inspector wants grounding bushings on the service conduits.",
    exEs: "El inspector quiere boquillas de tierra en los tubos de la acometida.",
  }),
  item("one-hole-strap", "fittings", "support", ["electrical", "plumbing"], ["One-hole strap", "one hole strap", "single-hole strap"], ["Abrazadera de un hoyo", "grapa de un orificio", "abrazadera de una pata"], {
    descEn: "A strap with a single screw hole that holds conduit or pipe against a surface.",
    descEs: "Abrazadera con un solo orificio que sujeta tubo contra una superficie.",
    useEn: "Secure conduit to walls, studs or strut near boxes and fittings.",
    useEs: "Se usa para fijar tubo a paredes, postes o strut cerca de cajas y accesorios.",
    exEn: "Strap it within three feet of the box with a one-hole.",
    exEs: "Sujétalo a menos de tres pies de la caja con una abrazadera de un hoyo.",
  }),
  item("two-hole-strap", "fittings", "support", ["electrical", "plumbing"], ["Two-hole strap", "two hole strap", "double-hole strap"], ["Abrazadera de dos hoyos", "grapa de dos orificios", "abrazadera de dos patas"], {
    descEn: "A U-shaped strap fastened with two screws, one on each side of the conduit.",
    descEs: "Abrazadera en forma de U que se fija con dos tornillos, uno a cada lado del tubo.",
    useEn: "Hold conduit or pipe firmly to a flat surface.",
    useEs: "Se usa para fijar firmemente tubo a una superficie plana.",
    exEn: "Use two-hole straps on the block wall.",
    exEs: "Usa abrazaderas de dos hoyos en la pared de block.",
  }),
  item("strut-channel", "hardware", "support", ["electrical", "plumbing", "hvac", "general"], ["Strut channel", "strut", "Unistrut", "Kindorf", "channel"], ["Canal strut", "unistrut", "canal unicanal", "riel strut"], {
    descEn: "A slotted galvanized steel channel used as a framing and support system.",
    descEs: "Canal de acero galvanizado ranurado que se usa como sistema de soporte.",
    useEn: "Build racks, trapezes and supports for conduit, pipe and equipment.",
    useEs: "Se usa para armar racks, trapecios y soportes para tubería y equipos.",
    exEn: "Cut me three pieces of strut at two feet.",
    exEs: "Córtame tres pedazos de strut de dos pies.",
    terms: ["unistrut"],
  }),
  item("strut-strap", "fittings", "support", ["electrical", "plumbing", "hvac"], ["Strut strap", "strut clamp", "pipe clamp for strut", "unistrut strap"], ["Abrazadera para strut", "abrazadera unistrut"], {
    descEn: "A two-piece clamp that locks conduit or pipe to strut channel.",
    descEs: "Abrazadera de dos piezas que fija tubo al canal strut.",
    useEn: "Secure conduit or pipe to a strut rack or trapeze.",
    useEs: "Se usa para asegurar tubo a un rack o trapecio de strut.",
    exEn: "Grab a box of three-quarter strut straps.",
    exEs: "Agarra una caja de abrazaderas para strut de tres cuartos.",
  }),
  item("beam-clamp", "hardware", "support", ["electrical", "plumbing", "hvac"], ["Beam clamp", "flange clamp", "I-beam clamp"], ["Abrazadera de viga", "clamp de viga", "prensa de viga"], {
    descEn: "A clamp that grips the flange of a steel beam without drilling.",
    descEs: "Abrazadera que se sujeta al ala de una viga de acero sin perforar.",
    useEn: "Hang threaded rod, conduit or supports from steel beams.",
    useEs: "Se usa para colgar varilla roscada, tubo o soportes de vigas de acero.",
    exEn: "Put a beam clamp on that I-beam and drop a rod.",
    exEs: "Pon una abrazadera de viga en esa viga y baja una varilla.",
  }),
  item("junction-box", "electrical", "box", ["electrical"], ["Junction box", "J-box", "j box", "pull box"], ["Caja de conexiones", "caja de empalme", "caja de registro", "caja J"], {
    descEn: "An enclosure where wires are spliced or pulled, closed with a cover.",
    descEs: "Caja donde se empalman o jalan cables, cerrada con una tapa.",
    useEn: "House splices and give access points along a wiring run.",
    useEs: "Aloja empalmes y da puntos de acceso a lo largo de una instalación.",
    exEn: "Put a junction box above the ceiling grid right there.",
    exEs: "Pon una caja de conexiones arriba del plafón justo ahí.",
  }),
  item("four-square-box", "electrical", "box", ["electrical"], ["4-square box", "four square box", "4x4 box", "1900 box"], ["Caja cuadrada 4x4", "caja cuatro por cuatro", "caja 4 square"], {
    descEn: "A 4-inch square metal box with multiple knockouts.",
    descEs: "Caja metálica cuadrada de 4 pulgadas con varios knockouts.",
    useEn: "Mount devices with a mud ring or serve as a junction point in commercial work.",
    useEs: "Se usa para montar dispositivos con anillo o como punto de empalme en obra comercial.",
    exEn: "Set a 4-square with a single-gang mud ring at every outlet.",
    exEs: "Pon una caja 4x4 con anillo sencillo en cada contacto.",
  }),
  item("handy-box", "electrical", "box", ["electrical"], ["Handy box", "utility box", "surface box"], ["Caja handy", "caja de superficie", "caja utilitaria"], {
    descEn: "A small surface-mount metal box with rounded edges for one device.",
    descEs: "Caja metálica pequeña de superficie con bordes redondeados para un dispositivo.",
    useEn: "Mount a single switch or receptacle on a surface, often with EMT.",
    useEs: "Se usa para montar un apagador o contacto en superficie, a menudo con EMT.",
    exEn: "Surface-mount a handy box on the block wall.",
    exEs: "Monta una caja handy en superficie en la pared de block.",
  }),
  item("octagon-box", "electrical", "box", ["electrical"], ["Octagon box", "octagonal box", "ceiling box", "light box"], ["Caja octagonal", "caja de techo", "caja para lámpara"], {
    descEn: "An eight-sided box typically mounted in ceilings.",
    descEs: "Caja de ocho lados que normalmente se monta en el techo.",
    useEn: "Support and connect light fixtures.",
    useEs: "Se usa para soportar y conectar lámparas.",
    exEn: "Every light gets an octagon box on a bar hanger.",
    exEs: "Cada lámpara lleva una caja octagonal con barra de soporte.",
  }),
  item("weatherproof-box", "electrical", "box", ["electrical"], ["Weatherproof box", "WP box", "bell box", "outdoor box"], ["Caja a prueba de agua", "caja intemperie", "caja exterior"], {
    descEn: "A cast metal box with threaded hubs, sealed for outdoor use.",
    descEs: "Caja de metal fundido con entradas roscadas, sellada para exteriores.",
    useEn: "Mount outdoor receptacles, switches and fixtures.",
    useEs: "Se usa para montar contactos, apagadores y lámparas en exteriores.",
    exEn: "Use a weatherproof box with an in-use cover outside.",
    exEs: "Afuera usa caja a prueba de agua con tapa de uso continuo.",
  }),
  item("wire-nut", "electrical", "connector", ["electrical"], ["Wire nut", "twist-on connector", "wire connector"], ["Capuchón", "conector de torsión", "tuerca para cable", "chupón"], {
    descEn: "A cone-shaped insulated connector twisted over stripped wire ends.",
    descEs: "Conector aislado en forma de cono que se enrosca sobre las puntas peladas.",
    useEn: "Splice two or more conductors together inside a box.",
    useEs: "Se usa para empalmar dos o más conductores dentro de una caja.",
    exEn: "Grab a bag of yellow wire nuts.",
    exEs: "Agarra una bolsa de capuchones amarillos.",
  }),
  item("lever-connector", "electrical", "connector", ["electrical"], ["Lever connector", "Wago", "lever nut", "push-in connector"], ["Conector de palanca", "wago", "conector rápido"], {
    descEn: "A splice connector with levers that clamp each stripped wire.",
    descEs: "Conector de empalme con palancas que sujetan cada cable pelado.",
    useEn: "Make quick, reusable splices without twisting wires.",
    useEs: "Se usa para hacer empalmes rápidos y reutilizables sin torcer cables.",
    exEn: "Use three-port lever connectors on the fixture whips.",
    exEs: "Usa conectores de palanca de tres puertos en los whips de las lámparas.",
    terms: ["wago"],
  }),
  item("fish-tape", "tools", "wire-pulling", ["electrical"], ["Fish tape", "snake", "electrician's snake", "draw tape"], ["Cinta guía", "cinta pasacables", "guía", "sonda", "pescador"], {
    descEn: "A long flat steel or fiberglass tape on a reel, pushed through conduit.",
    descEs: "Cinta larga de acero o fibra de vidrio en un carrete, que se empuja por el tubo.",
    useEn: "Pull wires or a pull string through conduit.",
    useEs: "Se usa para pasar cables o un cordel guía por el tubo.",
    exEn: "Run the fish tape from the panel to the box.",
    exEs: "Mete la cinta guía desde el panel hasta la caja.",
    terms: ["fish"],
  }),
  item("fish-rods", "tools", "wire-pulling", ["electrical"], ["Fish rods", "fish sticks", "glow rods", "push rods"], ["Varillas guía", "varillas pasacables", "varillas de fibra"], {
    descEn: "Screw-together fiberglass rods, often glow-in-the-dark.",
    descEs: "Varillas de fibra de vidrio que se enroscan entre sí, a menudo fluorescentes.",
    useEn: "Push wire through walls, ceilings and attics without conduit.",
    useEs: "Se usan para pasar cable por paredes, techos y áticos sin tubo.",
    exEn: "Use the fish rods to get across the drop ceiling.",
    exEs: "Usa las varillas guía para cruzar el plafón.",
  }),
  item("pull-string", "materials", "wire-pulling", ["electrical"], ["Pull string", "pull line", "mule tape", "jet line"], ["Cordel guía", "cuerda guía", "hilo de jalar"], {
    descEn: "A strong string or flat tape left inside conduit for future pulls.",
    descEs: "Cuerda o cinta resistente que se deja dentro del tubo para jalar después.",
    useEn: "Pull wire later through empty conduit runs.",
    useEs: "Se usa para jalar cable más adelante por tubos vacíos.",
    exEn: "Leave a pull string in every empty pipe.",
    exEs: "Deja un cordel guía en cada tubo vacío.",
  }),
  item("mc-cable", "electrical", "cable", ["electrical"], ["MC cable", "metal clad cable", "armored cable", "BX"], ["Cable MC", "cable armado", "cable blindado", "BX"], {
    descEn: "Insulated conductors inside an interlocking metal armor.",
    descEs: "Conductores aislados dentro de una armadura metálica entrelazada.",
    useEn: "Wire branch circuits in commercial buildings without conduit.",
    useEs: "Se usa para cablear circuitos en edificios comerciales sin tubo.",
    exEn: "Run twelve-two MC to each of these boxes.",
    exEs: "Corre MC doce-dos a cada una de estas cajas.",
  }),
  item("nm-b-cable", "electrical", "cable", ["electrical"], ["NM-B cable", "Romex", "non-metallic cable", "NM cable"], ["Cable NM-B", "romex", "cable no metálico"], {
    descEn: "Plastic-sheathed cable with insulated conductors and a bare ground.",
    descEs: "Cable con forro plástico, conductores aislados y una tierra desnuda.",
    useEn: "Wire circuits in residential wood-frame construction.",
    useEs: "Se usa para cablear circuitos en construcción residencial de madera.",
    exEn: "Pull fourteen-two Romex to the bedroom lights.",
    exEs: "Pasa romex catorce-dos a las luces de la recámara.",
    terms: ["romex"],
  }),
  item("thhn-wire", "electrical", "wire", ["electrical"], ["THHN wire", "building wire", "THHN", "single conductor"], ["Cable THHN", "alambre THHN", "cable de construcción"], {
    descEn: "Single insulated copper conductor with a nylon jacket.",
    descEs: "Conductor de cobre sencillo aislado con cubierta de nylon.",
    useEn: "Pull through conduit for power circuits.",
    useEs: "Se jala por el tubo para circuitos de fuerza.",
    exEn: "Pull three number twelve THHN plus a ground.",
    exEs: "Jala tres THHN calibre doce más una tierra.",
  }),
  item("ground-wire", "electrical", "wire", ["electrical"], ["Ground wire", "grounding conductor", "equipment ground", "green wire"], ["Cable de tierra", "tierra física", "cable verde"], {
    descEn: "A green or bare conductor that bonds equipment to ground.",
    descEs: "Conductor verde o desnudo que conecta los equipos a tierra.",
    useEn: "Provide a safe fault path back to the panel.",
    useEs: "Da un camino seguro para las fallas de regreso al panel.",
    exEn: "Every circuit gets its own green ground wire.",
    exEs: "Cada circuito lleva su propio cable de tierra verde.",
  }),
  item("circuit-breaker", "electrical", "protection", ["electrical"], ["Breaker", "circuit breaker", "CB"], ["Breaker", "interruptor termomagnético", "pastilla", "disyuntor"], {
    descEn: "A switch that trips automatically on overload or short circuit.",
    descEs: "Interruptor que se dispara automáticamente por sobrecarga o cortocircuito.",
    useEn: "Protect a circuit's wiring and turn it off for work.",
    useEs: "Protege el cableado de un circuito y sirve para apagarlo al trabajar.",
    exEn: "Kill the twenty-amp breaker before you touch it.",
    exEs: "Baja el breaker de veinte amperios antes de tocarlo.",
  }),
  item("receptacle", "electrical", "device", ["electrical"], ["Receptacle", "outlet", "plug", "duplex receptacle"], ["Contacto", "tomacorriente", "enchufe", "toma"], {
    descEn: "A device with slots where equipment plugs in to get power.",
    descEs: "Dispositivo con ranuras donde se conectan los equipos para recibir energía.",
    useEn: "Provide plug-in power along walls.",
    useEs: "Da energía para conectar equipos en las paredes.",
    exEn: "Install the receptacles eighteen inches off the floor.",
    exEs: "Instala los contactos a dieciocho pulgadas del piso.",
  }),
  item("gfci-receptacle", "electrical", "device", ["electrical"], ["GFCI receptacle", "GFCI", "GFI", "ground fault outlet"], ["Contacto GFCI", "contacto con falla a tierra", "GFI"], {
    descEn: "A receptacle with test/reset buttons that trips on ground faults.",
    descEs: "Contacto con botones de prueba y reset que se dispara por falla a tierra.",
    useEn: "Protect people from shock in wet areas like kitchens, baths and outdoors.",
    useEs: "Protege contra descargas en áreas húmedas como cocinas, baños y exteriores.",
    exEn: "The bathroom needs a GFCI on the first outlet.",
    exEs: "El baño necesita un GFCI en el primer contacto.",
  }),
  item("light-switch", "electrical", "device", ["electrical"], ["Switch", "light switch", "single-pole switch", "toggle switch"], ["Apagador", "interruptor", "switch"], {
    descEn: "A device that opens and closes a circuit to control a load.",
    descEs: "Dispositivo que abre y cierra un circuito para controlar una carga.",
    useEn: "Turn lights and equipment on and off.",
    useEs: "Se usa para prender y apagar luces y equipos.",
    exEn: "Put a three-way switch at each end of the hallway.",
    exEs: "Pon un apagador de tres vías en cada extremo del pasillo.",
  }),
  item("disconnect-switch", "electrical", "protection", ["electrical", "hvac"], ["Disconnect", "disconnect switch", "safety switch", "AC disconnect"], ["Desconectador", "interruptor de seguridad", "disconnect"], {
    descEn: "A lockable switch box that cuts all power to a piece of equipment.",
    descEs: "Caja con interruptor, que se puede bloquear, y corta toda la energía de un equipo.",
    useEn: "Isolate equipment such as condensers or motors for service.",
    useEs: "Aísla equipos como condensadoras o motores para darles servicio.",
    exEn: "Mount the disconnect within sight of the condenser.",
    exEs: "Monta el desconectador a la vista de la condensadora.",
  }),
  item("panelboard", "electrical", "distribution", ["electrical"], ["Panelboard", "panel", "breaker panel", "load center", "electrical panel"], ["Tablero eléctrico", "panel", "centro de carga", "tablero de breakers"], {
    descEn: "A cabinet with bus bars that holds the circuit breakers.",
    descEs: "Gabinete con barras que aloja los breakers.",
    useEn: "Distribute power from the feeder to individual circuits.",
    useEs: "Distribuye la energía del alimentador a cada circuito.",
    exEn: "Label every circuit in the panelboard directory.",
    exEs: "Etiqueta cada circuito en el directorio del tablero.",
  }),
  item("ground-bar", "electrical", "distribution", ["electrical"], ["Ground bar", "grounding bar", "ground bus"], ["Barra de tierra", "bus de tierra"], {
    descEn: "A metal bar with screw terminals for ground conductors.",
    descEs: "Barra metálica con terminales de tornillo para los cables de tierra.",
    useEn: "Land and bond all equipment grounds in a panel.",
    useEs: "Se usa para conectar todas las tierras de los equipos en un panel.",
    exEn: "Land the grounds on the ground bar, not the neutral.",
    exEs: "Conecta las tierras en la barra de tierra, no en el neutro.",
  }),
  item("multimeter", "tools", "testing", ["electrical", "hvac"], ["Multimeter", "meter", "voltmeter", "DMM", "clamp meter"], ["Multímetro", "tester", "voltímetro", "amperímetro de gancho"], {
    descEn: "A handheld tester that measures voltage, current and resistance.",
    descEs: "Probador de mano que mide voltaje, corriente y resistencia.",
    useEn: "Verify a circuit is dead and troubleshoot problems.",
    useEs: "Se usa para verificar que un circuito esté muerto y encontrar fallas.",
    exEn: "Check it with the multimeter before you open the box.",
    exEs: "Revísalo con el multímetro antes de abrir la caja.",
  }),
  item("lineman-pliers", "tools", "hand-tool", ["electrical"], ["Lineman's pliers", "linesman pliers", "side cutters", "Kleins", "linemans"], ["Pinza de electricista", "pinza universal", "alicate de electricista"], {
    descEn: "Heavy square-nosed pliers with a cutting edge near the pivot.",
    descEs: "Pinza pesada de punta cuadrada con filo de corte cerca del eje.",
    useEn: "Cut, twist and grip wire.",
    useEs: "Se usa para cortar, torcer y agarrar cables.",
    exEn: "Twist them together with your lineman's first.",
    exEs: "Tuércelos primero con la pinza de electricista.",
  }),
  item("diagonal-cutters", "tools", "hand-tool", ["electrical"], ["Diagonal cutters", "dikes", "wire cutters", "diagonal pliers", "snips"], ["Pinza de corte diagonal", "alicate de corte", "cortafrío", "pinza de corte"], {
    descEn: "Pliers with angled jaws designed only for cutting.",
    descEs: "Pinza con mordazas en ángulo diseñada solo para cortar.",
    useEn: "Cut wire, zip ties and small cable flush.",
    useEs: "Se usa para cortar cable, cinchos y cables delgados al ras.",
    exEn: "Snip those zip ties with the dikes.",
    exEs: "Corta esos cinchos con la pinza de corte.",
    terms: ["dikes"],
  }),
  item("wire-stripper", "tools", "hand-tool", ["electrical"], ["Wire stripper", "strippers", "wire strippers"], ["Pelacables", "pinza peladora", "desforrador"], {
    descEn: "A hand tool with sized notches that remove wire insulation.",
    descEs: "Herramienta de mano con muescas por calibre que quita el aislamiento.",
    useEn: "Strip insulation off conductors without nicking the copper.",
    useEs: "Se usa para pelar el aislamiento sin dañar el cobre.",
    exEn: "Strip about three-quarter inch with the strippers.",
    exEs: "Pela como tres cuartos de pulgada con el pelacables.",
  }),
  item("tongue-and-groove-pliers", "tools", "hand-tool", ["general", "plumbing", "electrical"], ["Tongue-and-groove pliers", "channel locks", "Channellocks", "water pump pliers", "slip-joint pliers"], ["Pinza ajustable", "pinza de canal", "alicate ajustable", "pinza pico de loro"], {
    descEn: "Adjustable pliers with angled jaws that slide along grooved channels.",
    descEs: "Pinza ajustable con mordazas en ángulo que se deslizan en canales.",
    useEn: "Grip and turn pipes, nuts and fittings of different sizes.",
    useEs: "Se usa para agarrar y girar tubos, tuercas y accesorios de varios tamaños.",
    exEn: "Hand me the channel locks to tighten that fitting.",
    exEs: "Pásame la pinza de canal para apretar ese accesorio.",
    terms: ["channel lock"],
  }),
  item("step-bit", "tools", "drilling", ["electrical", "general"], ["Step bit", "step drill bit", "unibit", "cone bit"], ["Broca escalonada", "broca de pasos", "broca cónica"], {
    descEn: "A cone-shaped bit with stepped diameters for drilling sheet metal.",
    descEs: "Broca cónica con diámetros escalonados para perforar lámina.",
    useEn: "Drill clean holes of several sizes in boxes and panels.",
    useEs: "Se usa para hacer hoyos limpios de varios tamaños en cajas y paneles.",
    exEn: "Open that hole to seven-eighths with the step bit.",
    exEs: "Agranda ese hoyo a siete octavos con la broca escalonada.",
  }),
  item("hole-saw", "tools", "drilling", ["electrical", "plumbing", "carpentry", "general"], ["Hole saw", "holesaw", "hole cutter"], ["Sierra de copa", "broca de copa", "sierra perforadora", "copa"], {
    descEn: "A cup-shaped saw blade with a pilot bit, mounted on a drill.",
    descEs: "Sierra en forma de copa con broca guía, que se monta en el taladro.",
    useEn: "Cut large round holes in wood, drywall or metal.",
    useEs: "Se usa para cortar hoyos redondos grandes en madera, tablaroca o metal.",
    exEn: "Use the two-inch hole saw through the top plate.",
    exEs: "Usa la sierra de copa de dos pulgadas en la solera de arriba.",
  }),
  item("knockout-punch", "tools", "hand-tool", ["electrical"], ["Knockout punch", "KO punch", "Greenlee punch", "hydraulic knockout"], ["Ponchadora de knockouts", "sacabocados", "punzón para knockout"], {
    descEn: "A punch-and-die set driven by a screw or hydraulics to cut round holes in enclosures.",
    descEs: "Juego de punzón y dado, de tornillo o hidráulico, para cortar hoyos redondos en gabinetes.",
    useEn: "Make clean conduit entry holes in panels and boxes.",
    useEs: "Se usa para hacer entradas limpias de tubo en paneles y cajas.",
    exEn: "Punch a one-and-a-quarter knockout in the top of the panel.",
    exEs: "Haz un knockout de una y cuarto arriba del panel.",
  }),
  item("conduit-reamer", "tools", "hand-tool", ["electrical"], ["Conduit reamer", "reamer", "deburring tool"], ["Rimador", "escariador", "rima para tubo", "desbarbador"], {
    descEn: "A tool that removes the sharp burr inside a freshly cut conduit.",
    descEs: "Herramienta que quita la rebaba filosa dentro de un tubo recién cortado.",
    useEn: "Smooth cut conduit ends so they don't damage wire.",
    useEs: "Alisa los extremos cortados para que no dañen el cable.",
    exEn: "Ream every cut before you put the fitting on.",
    exEs: "Rima cada corte antes de poner el accesorio.",
  }),
  item("conduit-bender", "tools", "hand-tool", ["electrical"], ["Conduit bender", "hand bender", "pipe bender", "EMT bender"], ["Dobladora de tubo", "doblador de conduit", "dobladora EMT"], {
    descEn: "A curved shoe on a long handle for bending conduit by hand.",
    descEs: "Zapata curva con mango largo para doblar tubo a mano.",
    useEn: "Make 90s, offsets and saddles in EMT.",
    useEs: "Se usa para hacer 90s, offsets y sillas en EMT.",
    exEn: "Grab the three-quarter bender and make me a ninety.",
    exEs: "Agarra la dobladora de tres cuartos y hazme un noventa.",
  }),
];

const PLUMBING: ConstructionLibraryItemSeed[] = [
  item("pvc-pipe", "plumbing", "pipe", ["plumbing", "electrical"], ["PVC pipe", "PVC", "schedule 40 PVC"], ["Tubo PVC", "tubería PVC", "caño de PVC"], {
    descEn: "Rigid white or gray plastic pipe joined with primer and cement.",
    descEs: "Tubo de plástico rígido blanco o gris que se une con primer y pegamento.",
    useEn: "Carry drain, waste and vent lines, or cold water, and serve as underground conduit.",
    useEs: "Se usa para drenaje y ventilación, agua fría, o como tubo eléctrico subterráneo.",
    exEn: "We need ten feet of two-inch PVC for the drain.",
    exEs: "Necesitamos diez pies de PVC de dos pulgadas para el drenaje.",
  }),
  item("pvc-coupling", "fittings", "pipe-fitting", ["plumbing"], ["PVC coupling", "slip coupling", "PVC coupler"], ["Copla PVC", "cople PVC", "unión PVC", "cople de PVC"], {
    descEn: "A short sleeve that joins two PVC pipes end to end.",
    descEs: "Manguito corto que une dos tubos de PVC uno tras otro.",
    useEn: "Extend or repair a straight PVC run.",
    useEs: "Se usa para extender o reparar una corrida recta de PVC.",
    exEn: "Glue a PVC coupling on the end and keep going.",
    exEs: "Pega una copla PVC al final y sigue.",
  }),
  item("pvc-elbow", "fittings", "pipe-fitting", ["plumbing"], ["PVC elbow", "PVC ell", "90", "PVC 90", "PVC 45"], ["Codo PVC", "codo de 90", "codo de 45"], {
    descEn: "An angled PVC fitting, usually 90 or 45 degrees.",
    descEs: "Accesorio de PVC en ángulo, normalmente de 90 o 45 grados.",
    useEn: "Change the direction of a PVC pipe run.",
    useEs: "Se usa para cambiar la dirección de una corrida de PVC.",
    exEn: "Put a forty-five here and a ninety at the wall.",
    exEs: "Pon un codo de cuarenta y cinco aquí y uno de noventa en la pared.",
  }),
  item("pvc-tee", "fittings", "pipe-fitting", ["plumbing"], ["PVC tee", "PVC T", "sanitary tee"], ["Te de PVC", "T de PVC", "tee sanitaria"], {
    descEn: "A T-shaped PVC fitting with three openings.",
    descEs: "Accesorio de PVC en forma de T con tres bocas.",
    useEn: "Branch a line off a main PVC run.",
    useEs: "Se usa para sacar un ramal de una línea principal de PVC.",
    exEn: "Cut in a tee for the new sink drain.",
    exEs: "Mete una te para el drenaje del lavabo nuevo.",
  }),
  item("pex-pipe", "plumbing", "pipe", ["plumbing"], ["PEX pipe", "PEX", "PEX tubing", "cross-linked polyethylene"], ["Tubo PEX", "tubería PEX", "manguera PEX"], {
    descEn: "Flexible plastic water supply tubing, usually red, blue or white.",
    descEs: "Tubería plástica flexible para agua, normalmente roja, azul o blanca.",
    useEn: "Run hot and cold water supply lines with few fittings.",
    useEs: "Se usa para líneas de agua fría y caliente con pocos accesorios.",
    exEn: "Run blue PEX for cold and red for hot.",
    exEs: "Corre PEX azul para fría y rojo para caliente.",
  }),
  item("pex-coupling", "fittings", "pex-fitting", ["plumbing"], ["PEX coupling", "PEX fitting", "PEX coupler", "PEX splice"], ["Copla PEX", "cople PEX", "unión PEX", "conexión PEX"], {
    descEn: "A brass or plastic insert fitting that joins two PEX lines with crimp or expansion rings.",
    descEs: "Accesorio de latón o plástico que une dos tubos PEX con anillos de crimpado o expansión.",
    useEn: "Join or repair two sections of PEX.",
    useEs: "Se usa para unir o reparar dos tramos de PEX.",
    exEn: "Crimp a PEX coupling where it got cut.",
    exEs: "Crimpa una copla PEX donde se cortó.",
    terms: ["pex fitting"],
  }),
  item("pex-elbow", "fittings", "pex-fitting", ["plumbing"], ["PEX elbow", "PEX 90", "PEX ell"], ["Codo PEX", "codo de 90 PEX"], {
    descEn: "A 90-degree PEX fitting.",
    descEs: "Accesorio PEX de 90 grados.",
    useEn: "Make tight turns in PEX where the tubing can't bend.",
    useEs: "Se usa para vueltas cerradas donde el PEX no se puede doblar.",
    exEn: "Use a PEX elbow coming out of the wall.",
    exEs: "Usa un codo PEX al salir de la pared.",
  }),
  item("pex-tee", "fittings", "pex-fitting", ["plumbing"], ["PEX tee", "PEX T"], ["Te PEX", "T PEX"], {
    descEn: "A T-shaped PEX fitting with three connections.",
    descEs: "Accesorio PEX en forma de T con tres conexiones.",
    useEn: "Branch a water line to another fixture.",
    useEs: "Se usa para sacar un ramal de agua hacia otro mueble.",
    exEn: "Tee off the main line for the ice maker.",
    exEs: "Saca una te de la línea principal para la máquina de hielo.",
  }),
  item("copper-pipe", "plumbing", "pipe", ["plumbing", "hvac"], ["Copper pipe", "copper tubing", "type L copper", "type M copper"], ["Tubo de cobre", "tubería de cobre", "caño de cobre"], {
    descEn: "Rigid or soft copper tube joined by soldering or press fittings.",
    descEs: "Tubo de cobre rígido o flexible que se une con soldadura o accesorios de prensa.",
    useEn: "Carry water supply lines and refrigerant lines.",
    useEs: "Se usa para líneas de agua y de refrigerante.",
    exEn: "Sweat in a new piece of three-quarter copper.",
    exEs: "Suelda un pedazo nuevo de cobre de tres cuartos.",
  }),
  item("copper-coupling", "fittings", "pipe-fitting", ["plumbing"], ["Copper coupling", "sweat coupling", "slip coupling copper"], ["Copla de cobre", "cople de cobre", "unión de cobre"], {
    descEn: "A copper sleeve soldered over two pipe ends to join them.",
    descEs: "Manguito de cobre que se suelda sobre dos tubos para unirlos.",
    useEn: "Join or repair straight copper runs.",
    useEs: "Se usa para unir o reparar corridas rectas de cobre.",
    exEn: "Clean it good before you sweat the coupling.",
    exEs: "Límpialo bien antes de soldar la copla.",
  }),
  item("ball-valve", "plumbing", "valve", ["plumbing", "hvac"], ["Ball valve", "quarter-turn valve", "full port valve"], ["Válvula de bola", "válvula de esfera", "llave de paso de bola"], {
    descEn: "A quarter-turn valve with a drilled ball; handle in line with the pipe means open.",
    descEs: "Válvula de cuarto de vuelta con una bola perforada; manija alineada con el tubo es abierta.",
    useEn: "Shut off or open water or gas flow quickly.",
    useEs: "Se usa para cerrar o abrir rápido el paso de agua o gas.",
    exEn: "Close the ball valve before you cut the line.",
    exEs: "Cierra la válvula de bola antes de cortar la línea.",
  }),
  item("gate-valve", "plumbing", "valve", ["plumbing"], ["Gate valve", "wheel valve"], ["Válvula de compuerta", "llave de compuerta"], {
    descEn: "A multi-turn valve with a round handle that raises and lowers a gate.",
    descEs: "Válvula de varias vueltas con manija redonda que sube y baja una compuerta.",
    useEn: "Isolate a main water line when fully open or closed.",
    useEs: "Se usa para aislar una línea principal de agua, totalmente abierta o cerrada.",
    exEn: "The old gate valve won't hold; replace it with a ball valve.",
    exEs: "La válvula de compuerta vieja no cierra; cámbiala por una de bola.",
  }),
  item("shutoff-valve", "plumbing", "valve", ["plumbing"], ["Shutoff valve", "angle stop", "stop valve", "supply stop"], ["Llave de paso", "válvula de cierre", "llave angular"], {
    descEn: "A small valve under a fixture that controls its water supply.",
    descEs: "Válvula pequeña bajo un mueble sanitario que controla su suministro de agua.",
    useEn: "Turn off water to one toilet or sink without shutting the house.",
    useEs: "Se usa para cortar el agua de un inodoro o lavabo sin cerrar toda la casa.",
    exEn: "Put a quarter-turn angle stop under the sink.",
    exEs: "Pon una llave angular de cuarto de vuelta bajo el lavabo.",
  }),
  item("p-trap", "plumbing", "drain", ["plumbing"], ["P-trap", "trap", "sink trap"], ["Trampa P", "sifón", "trampa de lavabo", "cespol"], {
    descEn: "A U-shaped drain fitting that holds water to block sewer gas.",
    descEs: "Accesorio de drenaje en U que retiene agua para bloquear el gas del drenaje.",
    useEn: "Seal fixture drains against sewer gases.",
    useEs: "Sella los drenajes de los muebles contra los gases del drenaje.",
    exEn: "Install the P-trap and check it for leaks.",
    exEs: "Instala la trampa P y revisa que no gotee.",
  }),
  item("cleanout", "plumbing", "drain", ["plumbing"], ["Cleanout", "clean-out", "cleanout plug", "C.O."], ["Registro", "tapón de registro", "registro de limpieza"], {
    descEn: "An access fitting with a removable plug on a drain line.",
    descEs: "Accesorio de acceso con tapón removible en una línea de drenaje.",
    useEn: "Give access to snake and clear drain blockages.",
    useEs: "Da acceso para meter la guía y destapar el drenaje.",
    exEn: "Leave the cleanout accessible behind that panel.",
    exEs: "Deja el registro accesible detrás de ese panel.",
  }),
  item("pipe-wrench", "tools", "hand-tool", ["plumbing"], ["Pipe wrench", "Stillson", "Ridgid wrench"], ["Llave Stillson", "llave de tubo", "llave de tubería", "stilson"], {
    descEn: "A heavy adjustable wrench with serrated jaws that bite into round pipe.",
    descEs: "Llave ajustable pesada con mordazas dentadas que muerden el tubo redondo.",
    useEn: "Turn and hold threaded steel pipe and fittings.",
    useEs: "Se usa para girar y sostener tubo roscado de acero y accesorios.",
    exEn: "Back it up with a second pipe wrench.",
    exEs: "Sosténlo con otra llave Stillson.",
  }),
  item("basin-wrench", "tools", "hand-tool", ["plumbing"], ["Basin wrench", "sink wrench", "faucet wrench"], ["Llave de lavabo", "llave para grifo", "llave de lavamanos"], {
    descEn: "A long-shaft wrench with a pivoting jaw for tight spaces.",
    descEs: "Llave de eje largo con mordaza giratoria para espacios reducidos.",
    useEn: "Loosen and tighten faucet nuts behind a sink.",
    useEs: "Se usa para aflojar y apretar las tuercas del grifo detrás del lavabo.",
    exEn: "You'll need the basin wrench to reach that nut.",
    exEs: "Vas a necesitar la llave de lavabo para alcanzar esa tuerca.",
  }),
  item("pipe-cutter", "tools", "hand-tool", ["plumbing", "hvac"], ["Pipe cutter", "tubing cutter", "copper cutter", "PVC cutter"], ["Cortatubos", "cortador de tubo", "cortador de cobre"], {
    descEn: "A clamp-style tool with a cutting wheel that rotates around the pipe.",
    descEs: "Herramienta tipo prensa con rueda de corte que gira alrededor del tubo.",
    useEn: "Make clean, square cuts on copper, PEX or PVC.",
    useEs: "Se usa para hacer cortes limpios y rectos en cobre, PEX o PVC.",
    exEn: "Cut it square with the tubing cutter, not the hacksaw.",
    exEs: "Córtalo derecho con el cortatubos, no con la segueta.",
  }),
];

const HVAC: ConstructionLibraryItemSeed[] = [
  item("air-handler", "equipment", "hvac-unit", ["hvac"], ["Air handler", "AHU", "air handling unit", "fan coil"], ["Manejadora de aire", "unidad manejadora", "evaporadora", "UMA"], {
    descEn: "The indoor HVAC unit with a blower and coil that moves conditioned air.",
    descEs: "Unidad interior de HVAC con ventilador y serpentín que mueve el aire acondicionado.",
    useEn: "Blow heated or cooled air through the ductwork.",
    useEs: "Impulsa el aire frío o caliente por los ductos.",
    exEn: "Set the air handler on the platform in the attic.",
    exEs: "Pon la manejadora en la plataforma del ático.",
  }),
  item("condenser", "equipment", "hvac-unit", ["hvac"], ["Condenser", "condensing unit", "outdoor unit", "AC unit"], ["Condensadora", "unidad condensadora", "unidad exterior"], {
    descEn: "The outdoor AC unit with the compressor, coil and fan.",
    descEs: "Unidad exterior del aire acondicionado con compresor, serpentín y ventilador.",
    useEn: "Reject heat from the building to the outside air.",
    useEs: "Saca el calor del edificio hacia el aire exterior.",
    exEn: "Set the condenser on the pad and level it.",
    exEs: "Pon la condensadora en la base y nivélala.",
  }),
  item("thermostat", "hvac", "controls", ["hvac", "electrical"], ["Thermostat", "t-stat", "tstat"], ["Termostato"], {
    descEn: "A wall control that senses temperature and switches the HVAC system.",
    descEs: "Control de pared que mide la temperatura y enciende el sistema HVAC.",
    useEn: "Set and hold the room temperature.",
    useEs: "Se usa para fijar y mantener la temperatura del cuarto.",
    exEn: "Mount the thermostat five feet off the floor on an inside wall.",
    exEs: "Monta el termostato a cinco pies del piso en una pared interior.",
  }),
  item("flex-duct", "hvac", "duct", ["hvac"], ["Flex duct", "flexible duct", "flex"], ["Ducto flexible", "flex", "manguera de ducto"], {
    descEn: "Insulated flexible round duct with a wire coil and plastic jacket.",
    descEs: "Ducto redondo flexible y aislado con espiral de alambre y forro plástico.",
    useEn: "Connect supply and return registers to the trunk line.",
    useEs: "Se usa para conectar rejillas de inyección y retorno al ducto principal.",
    exEn: "Pull the flex tight and strap it every four feet.",
    exEs: "Estira bien el flexible y sujétalo cada cuatro pies.",
  }),
  item("rigid-duct", "hvac", "duct", ["hvac"], ["Rigid duct", "sheet metal duct", "hard duct", "trunk line"], ["Ducto rígido", "ducto de lámina", "ducto metálico", "troncal"], {
    descEn: "Round or rectangular galvanized sheet-metal duct.",
    descEs: "Ducto de lámina galvanizada, redondo o rectangular.",
    useEn: "Carry air along main trunk runs with low resistance.",
    useEs: "Lleva el aire por las troncales principales con poca resistencia.",
    exEn: "Seal every seam on the rigid duct with mastic.",
    exEs: "Sella cada unión del ducto rígido con mastique.",
  }),
  item("register", "hvac", "air-outlet", ["hvac"], ["Register", "air register", "floor register"], ["Rejilla", "registro de aire", "rejilla con compuerta"], {
    descEn: "A grille with an adjustable damper that covers a duct opening.",
    descEs: "Rejilla con compuerta ajustable que cubre la boca de un ducto.",
    useEn: "Deliver and control airflow into a room.",
    useEs: "Entrega y regula el flujo de aire hacia un cuarto.",
    exEn: "Install a four-by-ten register under the window.",
    exEs: "Instala una rejilla de cuatro por diez bajo la ventana.",
  }),
  item("supply-vent", "hvac", "air-outlet", ["hvac"], ["Supply vent", "supply diffuser", "diffuser", "supply grille"], ["Difusor de inyección", "rejilla de suministro", "difusor"], {
    descEn: "A ceiling or wall outlet that spreads conditioned air into a room.",
    descEs: "Salida de techo o pared que distribuye el aire acondicionado en un cuarto.",
    useEn: "Distribute supply air evenly across a space.",
    useEs: "Distribuye el aire de inyección de forma pareja en el espacio.",
    exEn: "Drop a supply diffuser in each ceiling tile we marked.",
    exEs: "Pon un difusor en cada placa de plafón que marcamos.",
  }),
  item("return-vent", "hvac", "air-outlet", ["hvac"], ["Return vent", "return grille", "return air grille", "filter grille"], ["Rejilla de retorno", "retorno", "rejilla de retorno con filtro"], {
    descEn: "A larger grille where room air goes back to the air handler.",
    descEs: "Rejilla más grande por donde el aire del cuarto regresa a la manejadora.",
    useEn: "Pull air back to the system to keep airflow balanced.",
    useEs: "Regresa el aire al sistema para mantener el flujo balanceado.",
    exEn: "The return grille goes in the hallway ceiling.",
    exEs: "La rejilla de retorno va en el techo del pasillo.",
  }),
  item("line-set", "hvac", "refrigerant", ["hvac"], ["Line set", "lineset", "refrigerant line set"], ["Juego de líneas", "line set", "tubería de refrigeración"], {
    descEn: "A pair of copper refrigerant lines, the larger one insulated.",
    descEs: "Par de tubos de cobre de refrigerante; el más grueso va aislado.",
    useEn: "Connect the outdoor condenser to the indoor coil.",
    useEs: "Conecta la condensadora exterior con el serpentín interior.",
    exEn: "Run the line set through the wall and seal the hole.",
    exEs: "Pasa el juego de líneas por la pared y sella el hoyo.",
  }),
  item("refrigerant-line", "hvac", "refrigerant", ["hvac"], ["Refrigerant line", "suction line", "liquid line", "copper line"], ["Línea de refrigerante", "línea de succión", "línea de líquido"], {
    descEn: "A single copper tube that carries refrigerant: the large suction or the small liquid line.",
    descEs: "Tubo de cobre que lleva refrigerante: la línea gruesa de succión o la delgada de líquido.",
    useEn: "Move refrigerant between the compressor and the evaporator coil.",
    useEs: "Mueve el refrigerante entre el compresor y el serpentín evaporador.",
    exEn: "Insulate the suction line all the way to the coil.",
    exEs: "Aísla la línea de succión hasta el serpentín.",
  }),
  item("condensate-line", "hvac", "drain", ["hvac", "plumbing"], ["Condensate line", "condensate drain", "AC drain line"], ["Línea de condensado", "drenaje del aire", "tubo de condensado"], {
    descEn: "A small drain pipe, usually PVC, from the coil's drain pan.",
    descEs: "Tubo de drenaje pequeño, normalmente PVC, que sale de la charola del serpentín.",
    useEn: "Carry water produced by the cooling coil to a drain.",
    useEs: "Lleva el agua que produce el serpentín hacia un drenaje.",
    exEn: "Slope the condensate line and add a trap.",
    exEs: "Dale pendiente a la línea de condensado y ponle trampa.",
  }),
  item("air-filter", "hvac", "filtration", ["hvac"], ["Filter", "air filter", "furnace filter", "HVAC filter"], ["Filtro", "filtro de aire"], {
    descEn: "A framed pleated media panel that traps dust from return air.",
    descEs: "Panel de material plisado con marco que atrapa el polvo del aire de retorno.",
    useEn: "Keep the coil and blower clean and the air healthier.",
    useEs: "Mantiene limpio el serpentín y el ventilador y mejora el aire.",
    exEn: "Check the arrow; the filter goes toward the unit.",
    exEs: "Fíjate en la flecha; el filtro va hacia la unidad.",
  }),
  item("duct-strap", "hvac", "support", ["hvac"], ["Duct strap", "hanger strap", "plumber's tape", "strap"], ["Fleje para ducto", "cinta perforada", "fleje", "cinta de colgar"], {
    descEn: "Perforated metal or nylon strap used to hang ducts.",
    descEs: "Cinta metálica perforada o de nylon que se usa para colgar ductos.",
    useEn: "Support ducts and pipes from joists and trusses.",
    useEs: "Se usa para colgar ductos y tubos de vigas y armaduras.",
    exEn: "Hang the trunk with duct strap every five feet.",
    exEs: "Cuelga la troncal con fleje cada cinco pies.",
  }),
];

const GENERAL_TOOLS: ConstructionLibraryItemSeed[] = [
  item("impact-driver", "tools", "power-tool", ["general", "electrical", "carpentry", "hvac", "plumbing"], ["Impact driver", "impact", "impact gun"], ["Atornillador de impacto", "impacto", "pistola de impacto", "llave de impacto"], {
    descEn: "A compact cordless driver that adds rotational impacts for high torque.",
    descEs: "Atornillador inalámbrico compacto que da golpes rotativos para mucho torque.",
    useEn: "Drive long screws, lag bolts and anchors fast.",
    useEs: "Se usa para meter tornillos largos, pijas y anclas rápido.",
    exEn: "Use the impact to drive those lag screws.",
    exEs: "Usa el impacto para meter esas pijas.",
  }),
  item("drill", "tools", "power-tool", ["general", "electrical", "carpentry", "plumbing", "hvac"], ["Drill", "drill driver", "cordless drill", "power drill"], ["Taladro", "taladro inalámbrico", "rotomartillo"], {
    descEn: "A power tool with an adjustable chuck that spins drill bits.",
    descEs: "Herramienta eléctrica con mandril ajustable que hace girar brocas.",
    useEn: "Drill holes and drive screws with clutch control.",
    useEs: "Se usa para perforar y atornillar con control de embrague.",
    exEn: "Grab the drill and a quarter-inch bit.",
    exEs: "Agarra el taladro y una broca de un cuarto.",
  }),
  item("hammer", "tools", "hand-tool", ["general", "carpentry"], ["Hammer", "claw hammer", "framing hammer"], ["Martillo", "martillo de uña"], {
    descEn: "A hand tool with a weighted head and a claw for pulling nails.",
    descEs: "Herramienta de mano con cabeza pesada y uña para sacar clavos.",
    useEn: "Drive and pull nails.",
    useEs: "Se usa para clavar y sacar clavos.",
    exEn: "Toss me the framing hammer.",
    exEs: "Aviéntame el martillo de carpintero.",
  }),
  item("sledgehammer", "tools", "hand-tool", ["general", "concrete"], ["Sledgehammer", "sledge", "mall", "maul"], ["Marro", "mazo", "almádena", "porra"], {
    descEn: "A long-handled hammer with a heavy flat head.",
    descEs: "Martillo de mango largo con cabeza plana y pesada.",
    useEn: "Break concrete and masonry or drive stakes.",
    useEs: "Se usa para romper concreto y block o clavar estacas.",
    exEn: "Break out that slab with the sledgehammer.",
    exEs: "Rompe esa losa con el marro.",
  }),
  item("circular-saw", "tools", "power-tool", ["general", "carpentry"], ["Circular saw", "Skilsaw", "skill saw", "worm drive"], ["Sierra circular", "skil", "sierra eléctrica"], {
    descEn: "A handheld power saw with a round toothed blade.",
    descEs: "Sierra eléctrica de mano con disco dentado.",
    useEn: "Make straight cuts in lumber and plywood.",
    useEs: "Se usa para cortes rectos en madera y triplay.",
    exEn: "Rip that plywood with the circular saw.",
    exEs: "Corta ese triplay a lo largo con la sierra circular.",
    terms: ["skilsaw"],
  }),
  item("reciprocating-saw", "tools", "power-tool", ["general", "electrical", "plumbing", "carpentry"], ["Reciprocating saw", "Sawzall", "recip saw", "sawsall"], ["Sierra reciprocante", "sawzall", "sierra sable", "segueta eléctrica"], {
    descEn: "A power saw whose straight blade moves back and forth.",
    descEs: "Sierra eléctrica cuya hoja recta se mueve hacia adelante y atrás.",
    useEn: "Demolition and cutting pipe, studs and nails in place.",
    useEs: "Se usa en demolición y para cortar tubo, postes y clavos en sitio.",
    exEn: "Cut that old pipe out with the Sawzall.",
    exEs: "Corta ese tubo viejo con la sawzall.",
    terms: ["sawzall"],
  }),
  item("oscillating-multi-tool", "tools", "power-tool", ["general", "carpentry", "drywall", "flooring"], ["Oscillating multi-tool", "multi-tool", "oscillating tool", "multimaster"], ["Multiherramienta oscilante", "herramienta oscilante", "multiherramienta"], {
    descEn: "A power tool whose accessory vibrates side to side at high speed.",
    descEs: "Herramienta eléctrica cuyo accesorio vibra de lado a lado a alta velocidad.",
    useEn: "Make plunge and flush cuts in tight spots.",
    useEs: "Se usa para cortes de inmersión y al ras en espacios reducidos.",
    exEn: "Undercut the door jamb with the multi-tool.",
    exEs: "Recorta el marco de la puerta con la multiherramienta.",
  }),
  item("angle-grinder", "tools", "power-tool", ["general", "concrete", "electrical", "tile"], ["Angle grinder", "grinder", "4-1/2 grinder", "side grinder"], ["Esmeriladora", "pulidora", "amoladora", "esmeril angular"], {
    descEn: "A handheld power tool that spins an abrasive or cutting disc.",
    descEs: "Herramienta eléctrica de mano que hace girar un disco abrasivo o de corte.",
    useEn: "Cut metal, rebar, tile and grind welds or edges.",
    useEs: "Se usa para cortar metal, varilla, azulejo y desbastar bordes.",
    exEn: "Cut the all-thread with the grinder and a cut-off wheel.",
    exEs: "Corta la varilla roscada con la esmeriladora y un disco de corte.",
  }),
  item("utility-knife", "tools", "hand-tool", ["general", "drywall", "flooring", "roofing"], ["Utility knife", "box cutter", "razor knife"], ["Cúter", "navaja", "cutter", "cuchilla"], {
    descEn: "A knife with a replaceable, often retractable, razor blade.",
    descEs: "Navaja con hoja reemplazable, a menudo retráctil.",
    useEn: "Score drywall, cut cable jackets, cardboard and shingles.",
    useEs: "Se usa para marcar tablaroca y cortar forros, cartón y tejas.",
    exEn: "Score it with the utility knife and snap it.",
    exEs: "Márcalo con el cúter y quiébralo.",
  }),
  item("level", "tools", "measuring", ["general", "electrical", "carpentry", "tile", "concrete"], ["Level", "spirit level", "torpedo level", "bubble level"], ["Nivel", "nivel de burbuja", "nivel torpedo"], {
    descEn: "A straight tool with bubble vials that shows level and plumb.",
    descEs: "Herramienta recta con burbujas que muestra si algo está a nivel o a plomo.",
    useEn: "Check that work is level or plumb.",
    useEs: "Se usa para verificar que el trabajo esté a nivel o a plomo.",
    exEn: "Put the level on it before you screw it off.",
    exEs: "Ponle el nivel antes de atornillarlo.",
  }),
  item("tape-measure", "tools", "measuring", ["general", "electrical", "carpentry", "plumbing", "hvac", "flooring"], ["Tape measure", "tape", "measuring tape", "25-foot tape"], ["Cinta métrica", "flexómetro", "metro", "cinta de medir"], {
    descEn: "A retractable steel tape marked in feet, inches and fractions.",
    descEs: "Cinta de acero retráctil marcada en pies, pulgadas y fracciones.",
    useEn: "Measure lengths and layout on the job.",
    useEs: "Se usa para medir y trazar en la obra.",
    exEn: "Pull a tape from the wall to the center of the box.",
    exEs: "Mide con la cinta de la pared al centro de la caja.",
  }),
  item("framing-square", "tools", "measuring", ["carpentry", "general"], ["Framing square", "carpenter's square", "steel square"], ["Escuadra de carpintero", "escuadra de acero", "escuadra grande"], {
    descEn: "A large L-shaped steel square with measurement scales.",
    descEs: "Escuadra grande de acero en forma de L con escalas de medida.",
    useEn: "Lay out stairs, rafters and check corners for square.",
    useEs: "Se usa para trazar escaleras, vigas y revisar esquinas a escuadra.",
    exEn: "Check the corner with the framing square.",
    exEs: "Revisa la esquina con la escuadra de carpintero.",
  }),
  item("speed-square", "tools", "measuring", ["carpentry", "roofing", "general"], ["Speed square", "rafter square", "triangle square"], ["Escuadra rápida", "escuadra triangular", "escuadra de techo"], {
    descEn: "A small triangular square with degree markings.",
    descEs: "Escuadra triangular pequeña con marcas de grados.",
    useEn: "Mark square and angled cuts on lumber.",
    useEs: "Se usa para marcar cortes rectos y en ángulo en madera.",
    exEn: "Mark it with the speed square and cut it.",
    exEs: "Márcalo con la escuadra rápida y córtalo.",
  }),
  item("pry-bar", "tools", "hand-tool", ["general", "carpentry"], ["Pry bar", "crowbar", "flat bar", "wrecking bar"], ["Barreta", "pata de cabra", "palanca", "barra"], {
    descEn: "A steel bar with flattened, curved ends for leverage.",
    descEs: "Barra de acero con puntas planas y curvas para hacer palanca.",
    useEn: "Pry apart boards, pull nails and demo trim.",
    useEs: "Se usa para separar tablas, sacar clavos y quitar molduras.",
    exEn: "Pop that trim off with the flat bar.",
    exEs: "Quita esa moldura con la barreta.",
  }),
  item("screwdriver", "tools", "hand-tool", ["general", "electrical"], ["Screwdriver", "Phillips", "flathead", "multi-bit screwdriver"], ["Desarmador", "destornillador", "desarmador de cruz", "desarmador plano"], {
    descEn: "A hand tool with a tip that fits screw heads.",
    descEs: "Herramienta de mano con punta que encaja en la cabeza del tornillo.",
    useEn: "Drive and remove screws, including device and terminal screws.",
    useEs: "Se usa para meter y sacar tornillos, incluso los de terminales.",
    exEn: "Hand me the flathead to tighten the terminal.",
    exEs: "Pásame el desarmador plano para apretar la terminal.",
  }),
  item("adjustable-wrench", "tools", "hand-tool", ["general", "plumbing"], ["Adjustable wrench", "crescent wrench", "crescent", "adjustable spanner"], ["Llave ajustable", "perico", "llave inglesa", "llave crescent"], {
    descEn: "An open-end wrench with a jaw adjusted by a worm screw.",
    descEs: "Llave de boca con mordaza que se ajusta con un tornillo sinfín.",
    useEn: "Turn nuts and bolts of different sizes.",
    useEs: "Se usa para girar tuercas y tornillos de varios tamaños.",
    exEn: "Snug that nut up with the crescent.",
    exEs: "Aprieta esa tuerca con el perico.",
  }),
  item("socket-wrench", "tools", "hand-tool", ["general", "hvac"], ["Socket wrench", "ratchet", "socket set"], ["Matraca", "llave de dado", "juego de dados", "trinquete"], {
    descEn: "A ratcheting handle with interchangeable sockets.",
    descEs: "Mango de trinquete con dados intercambiables.",
    useEn: "Tighten and loosen bolts quickly.",
    useEs: "Se usa para apretar y aflojar pernos rápidamente.",
    exEn: "Get the ratchet and a half-inch socket.",
    exEs: "Trae la matraca y un dado de media.",
  }),
  item("ladder", "equipment", "access", ["general"], ["Ladder"], ["Escalera"], {
    descEn: "A climbing structure with rungs or steps.",
    descEs: "Estructura con peldaños para subir.",
    useEn: "Reach work above the floor safely.",
    useEs: "Se usa para alcanzar trabajo en altura de forma segura.",
    exEn: "Grab a ladder and check the ceiling box.",
    exEs: "Agarra una escalera y revisa la caja del techo.",
  }),
  item("extension-ladder", "equipment", "access", ["general", "roofing"], ["Extension ladder", "straight ladder", "28-foot ladder"], ["Escalera extensible", "escalera de extensión", "escalera recta"], {
    descEn: "A two-section ladder that slides to adjust its length; leans against a wall.",
    descEs: "Escalera de dos secciones que se desliza para ajustar su largo; se recarga en la pared.",
    useEn: "Reach roofs and high walls.",
    useEs: "Se usa para subir a techos y paredes altas.",
    exEn: "Tie off the extension ladder at the top.",
    exEs: "Amarra la escalera extensible arriba.",
  }),
  item("step-ladder", "equipment", "access", ["general", "electrical", "painting", "drywall"], ["Step ladder", "A-frame ladder", "6-foot ladder"], ["Escalera de tijera", "escalera tipo A", "escalera plegable"], {
    descEn: "A self-supporting folding ladder with flat steps.",
    descEs: "Escalera plegable autoportante con peldaños planos.",
    useEn: "Work on ceilings and walls indoors.",
    useEs: "Se usa para trabajar en techos y paredes en interiores.",
    exEn: "Use the six-foot step ladder, and don't stand on the top.",
    exEs: "Usa la escalera de tijera de seis pies, y no te pares en el último escalón.",
  }),
];

const PPE: ConstructionLibraryItemSeed[] = [
  item("hard-hat", "ppe", "head", ["general"], ["Hard hat", "helmet", "safety helmet"], ["Casco", "casco de seguridad"], {
    descEn: "A rigid protective helmet with an inner suspension.",
    descEs: "Casco rígido de protección con suspensión interior.",
    useEn: "Protect the head from falling objects and bumps.",
    useEs: "Protege la cabeza de objetos que caen y golpes.",
    exEn: "Hard hats on; they're working overhead.",
    exEs: "Pónganse el casco; están trabajando arriba.",
  }),
  item("safety-glasses", "ppe", "eye", ["general"], ["Safety glasses", "safety goggles", "eye protection"], ["Lentes de seguridad", "gafas de seguridad", "googles"], {
    descEn: "Impact-rated glasses that shield the eyes.",
    descEs: "Lentes resistentes a impactos que protegen los ojos.",
    useEn: "Protect eyes from dust, chips and debris.",
    useEs: "Protegen los ojos del polvo, rebabas y escombro.",
    exEn: "Safety glasses before you touch the grinder.",
    exEs: "Lentes de seguridad antes de tocar la esmeriladora.",
  }),
  item("work-gloves", "ppe", "hand", ["general"], ["Work gloves", "gloves", "cut-resistant gloves"], ["Guantes de trabajo", "guantes"], {
    descEn: "Gloves made to resist cuts, abrasion or punctures.",
    descEs: "Guantes hechos para resistir cortes, raspones o pinchazos.",
    useEn: "Protect hands when handling material and tools.",
    useEs: "Protegen las manos al manejar material y herramientas.",
    exEn: "Wear gloves when you handle that sheet metal.",
    exEs: "Usa guantes cuando agarres esa lámina.",
  }),
  item("safety-vest", "ppe", "visibility", ["general"], ["Safety vest", "hi-vis vest", "reflective vest"], ["Chaleco de seguridad", "chaleco reflejante", "chaleco"], {
    descEn: "A high-visibility vest with reflective stripes.",
    descEs: "Chaleco de alta visibilidad con franjas reflejantes.",
    useEn: "Make workers visible to equipment operators and traffic.",
    useEs: "Hace visibles a los trabajadores para operadores y tráfico.",
    exEn: "Vests on when you're near the lift.",
    exEs: "Pónganse el chaleco cerca del elevador.",
  }),
  item("safety-harness", "ppe", "fall-protection", ["general", "roofing"], ["Safety harness", "fall harness", "full-body harness"], ["Arnés de seguridad", "arnés", "arnés de cuerpo completo"], {
    descEn: "A full-body harness connected to an anchor with a lanyard.",
    descEs: "Arnés de cuerpo completo que se conecta a un anclaje con una línea.",
    useEn: "Arrest a fall when working at height.",
    useEs: "Detiene una caída al trabajar en altura.",
    exEn: "Tie off your harness before you step onto the roof.",
    exEs: "Amarra tu arnés antes de subirte al techo.",
  }),
];

const MATERIALS_AND_FASTENERS: ConstructionLibraryItemSeed[] = [
  item("drywall-sheet", "drywall", "board", ["drywall"], ["Drywall", "sheetrock", "gypsum board", "wallboard"], ["Tablaroca", "panel de yeso", "drywall", "placa de yeso"], {
    descEn: "Gypsum panels faced with paper, usually 4 by 8 or 4 by 12 feet.",
    descEs: "Paneles de yeso cubiertos de papel, normalmente de 4 por 8 o 4 por 12 pies.",
    useEn: "Finish interior walls and ceilings.",
    useEs: "Se usa para acabar paredes y techos interiores.",
    exEn: "Hang the twelve-foot sheetrock on the ceiling first.",
    exEs: "Cuelga primero la tablaroca de doce pies en el techo.",
    terms: ["sheetrock"],
  }),
  item("drywall-screw", "fasteners", "screw", ["drywall"], ["Drywall screw", "sheetrock screw", "bugle head screw"], ["Tornillo para tablaroca", "pija de tablaroca", "tornillo de drywall"], {
    descEn: "A black, fine or coarse thread screw with a bugle head.",
    descEs: "Tornillo negro, de rosca fina o gruesa, con cabeza de trompeta.",
    useEn: "Fasten drywall to studs without tearing the paper.",
    useEs: "Se usa para fijar tablaroca a los postes sin romper el papel.",
    exEn: "Coarse-thread drywall screws for the wood studs.",
    exEs: "Tornillos de rosca gruesa para los postes de madera.",
  }),
  item("metal-stud", "drywall", "framing", ["drywall", "carpentry"], ["Metal stud", "steel stud", "light-gauge stud"], ["Poste metálico", "canal metálico", "montante"], {
    descEn: "A C-shaped light-gauge steel framing member.",
    descEs: "Perfil de acero ligero en forma de C para estructura.",
    useEn: "Frame interior walls in commercial buildings.",
    useEs: "Se usa para armar paredes interiores en edificios comerciales.",
    exEn: "Put a metal stud on each side of the box.",
    exEs: "Pon un poste metálico a cada lado de la caja.",
  }),
  item("wood-stud", "carpentry", "framing", ["carpentry"], ["Wood stud", "2x4", "two-by-four", "stud"], ["Poste de madera", "barrote", "dos por cuatro", "polín"], {
    descEn: "A vertical dimensional lumber member in a wall frame.",
    descEs: "Pieza vertical de madera dimensionada en la estructura de una pared.",
    useEn: "Frame walls and give backing to fasten on.",
    useEs: "Se usa para armar paredes y dar respaldo para fijar.",
    exEn: "Toe-nail a two-by-four between the studs for blocking.",
    exEs: "Clava un dos por cuatro entre los postes como bloqueo.",
  }),
  item("plywood", "materials", "sheet-goods", ["carpentry", "roofing"], ["Plywood", "ply", "sheathing", "OSB"], ["Triplay", "madera contrachapada", "plywood", "OSB"], {
    descEn: "Panels made of thin glued wood layers, usually 4 by 8 feet.",
    descEs: "Paneles de capas delgadas de madera pegadas, normalmente de 4 por 8 pies.",
    useEn: "Sheath walls, roofs and subfloors or make backing boards.",
    useEs: "Se usa para forrar paredes, techos, pisos o como tablero de respaldo.",
    exEn: "Mount a sheet of plywood behind the panels.",
    exEs: "Monta una hoja de triplay detrás de los tableros.",
  }),
  item("concrete-anchor", "fasteners", "anchor", ["general", "electrical", "plumbing", "concrete"], ["Concrete anchor", "wedge anchor", "Tapcon", "drop-in anchor"], ["Ancla para concreto", "taquete", "ancla de expansión", "tapcon"], {
    descEn: "A fastener that expands or threads into drilled concrete or block.",
    descEs: "Sujetador que se expande o se enrosca en un hoyo en concreto o block.",
    useEn: "Attach supports, straps and equipment to concrete.",
    useEs: "Se usa para fijar soportes, abrazaderas y equipos al concreto.",
    exEn: "Use quarter-inch Tapcons on the block wall.",
    exEs: "Usa tapcons de un cuarto en la pared de block.",
    terms: ["tapcon"],
  }),
  item("threaded-rod", "hardware", "support", ["electrical", "plumbing", "hvac"], ["Threaded rod", "all-thread", "allthread", "ready rod"], ["Varilla roscada", "espárrago", "varilla de rosca corrida"], {
    descEn: "A steel rod threaded along its full length.",
    descEs: "Varilla de acero roscada en toda su longitud.",
    useEn: "Hang trapezes, pipe and duct from the structure.",
    useEs: "Se usa para colgar trapecios, tubería y ductos de la estructura.",
    exEn: "Drop three-eighths all-thread from the beam clamp.",
    exEs: "Baja varilla roscada de tres octavos desde la abrazadera de viga.",
  }),
  item("zip-tie", "hardware", "fastening", ["electrical", "general"], ["Zip tie", "cable tie", "tie wrap"], ["Cincho", "amarre plástico", "cincho plástico", "brida"], {
    descEn: "A nylon strap with a ratcheting head that locks when pulled.",
    descEs: "Tira de nylon con cabeza de trinquete que se traba al jalar.",
    useEn: "Bundle and secure cables neatly.",
    useEs: "Se usa para agrupar y sujetar cables de forma ordenada.",
    exEn: "Zip-tie the cables every couple of feet.",
    exEs: "Amarra los cables con cinchos cada par de pies.",
  }),
  item("electrical-tape", "materials", "tape", ["electrical"], ["Electrical tape", "vinyl tape", "friction tape", "phase tape"], ["Cinta de aislar", "teipe", "cinta aislante"], {
    descEn: "Stretchy vinyl tape that insulates and color-codes conductors.",
    descEs: "Cinta de vinil elástica que aísla y marca los conductores por color.",
    useEn: "Insulate splices and mark phases.",
    useEs: "Se usa para aislar empalmes y marcar fases.",
    exEn: "Phase-tape the neutrals white on the feeders.",
    exEs: "Marca los neutros con cinta blanca en los alimentadores.",
  }),
];

export const CONSTRUCTION_LIBRARY_SEED: readonly ConstructionLibraryItemSeed[] = [
  ...ELECTRICAL,
  ...PLUMBING,
  ...HVAC,
  ...GENERAL_TOOLS,
  ...PPE,
  ...MATERIALS_AND_FASTENERS,
];
