"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type LanguagePreference = "es" | "en";

interface LanguageContextValue {
  language: LanguagePreference;
  setLanguage: (lang: LanguagePreference) => void;
  t: (key: string) => string;
}

const T: Record<LanguagePreference, Record<string, string>> = {
  es: {
    // ── Roles ─────────────────────────────────────────────────────────────────
    "role.worker": "Profesional",
    "role.client": "Cliente",
    "role.admin": "Admin",

    // ── Nav items ─────────────────────────────────────────────────────────────
    "nav.dashboard": "Dashboard",
    "nav.operations": "Operaciones",
    "nav.autonomy": "Autonomía",
    "nav.developerRuntime": "Entorno Dev",
    "nav.communications": "Comunicaciones",
    "nav.domainEvents": "Eventos de dominio",
    "nav.users": "Usuarios",
    "nav.disputes": "Disputas",
    "nav.qaCenter": "Centro QA",
    "nav.compliance": "Cumplimiento",
    "nav.finance": "Finanzas",
    "nav.travelOps": "Viajes",
    "nav.reports": "Reportes",
    "nav.fieldOps": "Ops. de campo",
    "nav.settings": "Configuración",
    "nav.htmlCanvas": "HTML Canvas",
    "nav.buildOps": "BuildOps",
    "nav.semseTools": "SEMSE Tools",
    "nav.agents": "Agentes",
    "nav.coordinator": "Coordinador",
    "nav.llmMetrics": "Métricas LLM",
    "nav.missionControl": "Mission Control",
    "nav.algorithmEngine": "Algorithm Engine",
    "nav.aiMissionControl": "IA Mission Control",
    "nav.contractors": "Contractors / CRM",
    "nav.worker": "Worker / Jobs",
    "nav.consciousness": "Consciousness",
    "nav.pmo": "PMO Automatizado",
    "nav.semseX": "SEMSE_X",
    "nav.agentMemory": "Memoria Agente",
    "nav.prometeo": "Prometeo RAG",
    "nav.workerDashboard": "Dashboard",
    "nav.agenda": "Agenda",
    "nav.myJobs": "Mis trabajos",
    "nav.tasks": "Tareas",
    "nav.timeTracker": "Time Tracker",
    "nav.evidence": "Evidencia",
    "nav.materials": "Materiales",
    "nav.incidents": "Incidencias",
    "nav.payments": "Pagos",
    "nav.travel": "Movilidad",
    "nav.myProfile": "Mi perfil",
    "nav.aiSettings": "Asistente IA",
    "nav.leads": "Leads & Clientes",
    "nav.postJob": "Publicar trabajo",
    "nav.myProjects": "Mis proyectos",
    "nav.aiCopilot": "Copiloto IA",
    "nav.milestones": "Hitos",
    "nav.professionals": "Profesionales",
    "nav.documents": "Documentos",
    "nav.reviews": "Reseñas",
    "nav.financeHub": "Hub Financiero",

    // ── Sections ──────────────────────────────────────────────────────────────
    "section.main": "Principal",
    "section.control": "Control",
    "section.operations": "Operaciones",
    "section.field": "Campo",
    "section.ai": "IA",
    "section.lab": "Lab",

    // ── Common UI ─────────────────────────────────────────────────────────────
    "ui.signOut": "Salir",
    "ui.language": "Idioma",
    "ui.theme": "Tema",
    "ui.dark": "Oscuro",
    "ui.light": "Claro",
    "ui.notifications": "Notificaciones",
    "ui.loading": "Cargando…",
    "ui.save": "Guardar",
    "ui.cancel": "Cancelar",
    "ui.back": "Volver",
    "ui.new": "Nuevo",
    "ui.edit": "Editar",
    "ui.delete": "Eliminar",
    "ui.search": "Buscar",
    "ui.filter": "Filtrar",
    "ui.export": "Exportar",
    "ui.import": "Importar",
    "ui.refresh": "Actualizar",
    "ui.view": "Ver",
    "ui.add": "Agregar",
    "ui.create": "Crear",
    "ui.update": "Actualizar",
    "ui.confirm": "Confirmar",
    "ui.submit": "Enviar",
    "ui.approve": "Aprobar",
    "ui.reject": "Rechazar",
    "ui.resolve": "Resolver",
    "ui.open": "Abrir",
    "ui.close": "Cerrar",
    "ui.download": "Descargar",
    "ui.upload": "Subir",
    "ui.send": "Enviar",
    "ui.retry": "Reintentar",
    "ui.details": "Detalles",
    "ui.actions": "Acciones",
    "ui.status": "Estado",
    "ui.date": "Fecha",
    "ui.amount": "Monto",
    "ui.total": "Total",
    "ui.name": "Nombre",
    "ui.description": "Descripción",
    "ui.type": "Tipo",
    "ui.role": "Rol",
    "ui.email": "Correo",
    "ui.noData": "Sin datos disponibles",
    "ui.noResults": "Sin resultados",
    "ui.error": "Error",
    "ui.success": "Éxito",
    "ui.warning": "Advertencia",
    "ui.info": "Información",
    "ui.optional": "Opcional",
    "ui.required": "Requerido",
    "ui.all": "Todos",
    "ui.none": "Ninguno",
    "ui.yes": "Sí",
    "ui.no": "No",
    "ui.active": "Activo",
    "ui.inactive": "Inactivo",
    "ui.enabled": "Habilitado",
    "ui.disabled": "Deshabilitado",
    "ui.online": "En línea",
    "ui.offline": "Sin conexión",
    "ui.pending": "Pendiente",
    "ui.completed": "Completado",
    "ui.failed": "Fallido",
    "ui.cancelled": "Cancelado",
    "ui.more": "Más",
    "ui.less": "Menos",
    "ui.showMore": "Ver más",
    "ui.showLess": "Ver menos",
    "ui.seeAll": "Ver todo",
    "ui.back_to": "Volver a",
    "ui.since": "hace",
    "ui.ago": "hace",

    // ── Job status ────────────────────────────────────────────────────────────
    "status.draft": "Borrador",
    "status.posted": "Publicado",
    "status.reserved": "Reservado",
    "status.accepted": "Aceptado",
    "status.in_progress": "En progreso",
    "status.review": "En revisión",
    "status.dispute": "En disputa",
    "status.completed": "Completado",
    "status.cancelled": "Cancelado",
    "status.open": "Abierto",
    "status.closed": "Cerrado",
    "status.resolved": "Resuelto",
    "status.pending": "Pendiente",
    "status.approved": "Aprobado",
    "status.rejected": "Rechazado",
    "status.submitted": "Enviado",
    "status.funded": "Fondeado",
    "status.released": "Liberado",
    "status.running": "Ejecutando",
    "status.paused": "Pausado",
    "status.stopped": "Detenido",
    "status.failed": "Fallido",
    "status.queued": "En cola",

    // ── Pages — Admin ─────────────────────────────────────────────────────────
    "page.adminDashboard": "Panel de administración",
    "page.adminDashboard.sub": "Vista general de operaciones SEMSE",
    "page.operations": "Operaciones",
    "page.operations.sub": "Monitor de agentes y eventos de dominio",
    "page.autonomy": "Autonomía",
    "page.autonomy.sub": "Motor de autonomía agentiva",
    "page.developerRuntime": "Entorno Dev",
    "page.developerRuntime.sub": "Sesiones de ejecución del desarrollador",
    "page.compliance": "Cumplimiento",
    "page.compliance.sub": "Auditoría de contratos y licencias",
    "page.qaCenter": "Centro QA",
    "page.qaCenter.sub": "Control de calidad y validaciones",
    "page.disputes": "Disputas",
    "page.disputes.sub": "Gestión de conflictos entre partes",
    "page.users": "Usuarios",
    "page.users.sub": "Gestión de perfiles y roles",
    "page.finance": "Finanzas",
    "page.finance.sub": "Facturas, gastos y resumen financiero",
    "page.reports": "Reportes",
    "page.reports.sub": "Análisis y métricas de la plataforma",
    "page.settings": "Configuración",
    "page.settings.sub": "Ajustes del sistema SEMSE OS",
    "page.fieldOps": "Operaciones de campo",
    "page.fieldOps.sub": "Gestión de unidades y trabajo presencial",
    "page.travelOps": "Viajes",
    "page.travelOps.sub": "Gestión de desplazamientos y viáticos",
    "page.domainEvents": "Eventos de dominio",
    "page.domainEvents.sub": "Trazabilidad de eventos del sistema",
    "page.llmMetrics": "Métricas LLM",
    "page.llmMetrics.sub": "Rendimiento de modelos de lenguaje",
    "page.aiMissionControl": "Control Misión IA",
    "page.aiMissionControl.sub": "Centro de comando de agentes IA",
    "page.coordinator": "Coordinador",
    "page.coordinator.sub": "Agente coordinador de operaciones",
    "page.pmo": "PMO Automatizado",
    "page.pmo.sub": "Gestión de proyectos asistida por IA",
    "page.agentMemory": "Memoria de Agente",
    "page.agentMemory.sub": "Almacenamiento y recuperación de contexto agentivo",
    "page.prometeo": "Prometeo RAG",
    "page.prometeo.sub": "Base de conocimiento y recuperación semántica",

    // ── Pages — Worker ────────────────────────────────────────────────────────
    "page.workerDashboard": "Mi panel",
    "page.workerDashboard.sub": "Resumen de trabajo y actividad diaria",
    "page.myJobs": "Mis trabajos",
    "page.myJobs.sub": "Trabajos asignados y en progreso",
    "page.timeTracker": "Control de tiempo",
    "page.timeTracker.sub": "Registro de jornadas y horas trabajadas",
    "page.evidence": "Evidencia",
    "page.evidence.sub": "Fotos, documentos y archivos de obra",
    "page.materials": "Materiales",
    "page.materials.sub": "Solicitudes y seguimiento de materiales",
    "page.incidents": "Incidencias",
    "page.incidents.sub": "Reporte de problemas en campo",
    "page.workerPayments": "Mis pagos",
    "page.workerPayments.sub": "Escrow y liberaciones de pago",
    "page.workerTravel": "Movilidad",
    "page.workerTravel.sub": "Gestión de desplazamientos y viáticos",
    "page.workerFieldOps": "Operaciones de campo",
    "page.workerFieldOps.sub": "Unidades de trabajo y registro presencial",
    "page.agenda": "Agenda",
    "page.agenda.sub": "Calendario de trabajos y citas",
    "page.tasks": "Mis tareas",
    "page.tasks.sub": "Lista de tareas asignadas",
    "page.profile": "Mi perfil",
    "page.profile.sub": "Datos personales y configuración de cuenta",
    "page.aiAssistant": "Asistente IA",
    "page.aiAssistant.sub": "Preferencias del asistente inteligente",

    // ── Pages — Client ────────────────────────────────────────────────────────
    "page.clientDashboard": "Mi panel",
    "page.clientDashboard.sub": "Resumen de proyectos y actividad",
    "page.postJob": "Publicar trabajo",
    "page.postJob.sub": "Crear una nueva solicitud de servicio",
    "page.myProjects": "Mis proyectos",
    "page.myProjects.sub": "Trabajos activos y copiloto IA",
    "page.clientMilestones": "Mis hitos",
    "page.clientMilestones.sub": "Seguimiento de avances y aprobaciones",
    "page.clientPayments": "Pagos",
    "page.clientPayments.sub": "Historial de transacciones y escrow",
    "page.clientDisputes": "Disputas",
    "page.clientDisputes.sub": "Conflictos y resoluciones",
    "page.clientDocuments": "Documentos",
    "page.clientDocuments.sub": "Contratos, reportes y archivos",
    "page.clientFinance": "Finanzas",
    "page.clientFinance.sub": "Facturas y estado financiero",
    "page.professionals": "Profesionales",
    "page.professionals.sub": "Directorio de proveedores verificados",
    "page.reviews": "Reseñas",
    "page.reviews.sub": "Calificaciones y comentarios de trabajos",
    "page.leads": "Leads & Clientes",
    "page.leads.sub": "Pipeline de prospectos y clientes",

    // ── Pages — BuildOps ──────────────────────────────────────────────────────
    "page.buildOps": "BuildOps",
    "page.buildOps.sub": "Gestión de proyectos de construcción",
    "page.buildOpsProjects": "Proyectos",
    "page.buildOpsProjects.sub": "Lista de proyectos activos",
    "page.buildOpsMilestones": "Hitos de proyecto",
    "page.buildOpsMilestones.sub": "Seguimiento de avances por etapa",
    "page.buildOpsTasks": "Tareas",
    "page.buildOpsTasks.sub": "Lista de tareas del proyecto",

    // ── Pages — Tools ─────────────────────────────────────────────────────────
    "page.tools": "SEMSE Tools",
    "page.tools.sub": "Calculadoras profesionales por especialidad",
    "page.toolsDashboard": "Panel de herramientas",
    "page.toolsDashboard.sub": "Acceso a todos los motores de estimación",

    // ── Dashboard strings ─────────────────────────────────────────────────────
    "dash.quickActions": "Acciones rápidas",
    "dash.fastManagement": "Gestión rápida",
    "dash.fieldOpsDesc": "Ir a unidades y trabajo de campo",
    "dash.recentActivity": "Actividad reciente",
    "dash.summary": "Resumen",
    "dash.metrics": "Métricas",
    "dash.alerts": "Alertas",
    "dash.noAlerts": "Sin alertas activas",
    "dash.lastRefresh": "Última actualización",
    "dash.totalJobs": "Total de trabajos",
    "dash.activeJobs": "Trabajos activos",
    "dash.completedJobs": "Trabajos completados",
    "dash.totalUsers": "Total de usuarios",
    "dash.openDisputes": "Disputas abiertas",
    "dash.revenue": "Ingresos",

    // ── Operations ────────────────────────────────────────────────────────────
    "ops.agentRuns": "Ejecuciones de agente",
    "ops.pendingApprovals": "Aprobaciones pendientes",
    "ops.requeue": "Reencolar",
    "ops.retry": "Reintentar",
    "ops.approve": "Aprobar",
    "ops.reject": "Rechazar",
    "ops.openIncident": "Abrir incidente",
    "ops.runStatus": "Estado de ejecución",
    "ops.agentType": "Tipo de agente",
    "ops.noRuns": "Sin ejecuciones recientes",
    "ops.noApprovals": "Sin aprobaciones pendientes",

    // ── Jobs ──────────────────────────────────────────────────────────────────
    "job.title": "Título",
    "job.budget": "Presupuesto",
    "job.status": "Estado",
    "job.client": "Cliente",
    "job.worker": "Profesional",
    "job.created": "Creado",
    "job.updated": "Actualizado",
    "job.noJobs": "Sin trabajos disponibles",
    "job.newJob": "Nuevo trabajo",
    "job.viewJob": "Ver trabajo",
    "job.postJob": "Publicar trabajo",
    "job.scope": "Alcance",
    "job.location": "Ubicación",

    // ── Milestones ────────────────────────────────────────────────────────────
    "milestone.title": "Nombre del hito",
    "milestone.amount": "Monto",
    "milestone.status": "Estado",
    "milestone.sequence": "Secuencia",
    "milestone.submit": "Enviar",
    "milestone.approve": "Aprobar",
    "milestone.reject": "Rechazar",
    "milestone.release": "Liberar pago",
    "milestone.noMilestones": "Sin hitos creados",
    "milestone.create": "Crear hito",

    // ── Evidence ──────────────────────────────────────────────────────────────
    "evidence.kind": "Tipo de evidencia",
    "evidence.filename": "Nombre de archivo",
    "evidence.upload": "Subir evidencia",
    "evidence.register": "Registrar evidencia",
    "evidence.noEvidence": "Sin evidencia registrada",
    "evidence.photo": "Foto",
    "evidence.document": "Documento",
    "evidence.video": "Video",

    // ── Finance ───────────────────────────────────────────────────────────────
    "finance.invoice": "Factura",
    "finance.invoices": "Facturas",
    "finance.expense": "Gasto",
    "finance.expenses": "Gastos",
    "finance.amount": "Monto",
    "finance.paid": "Pagado",
    "finance.unpaid": "No pagado",
    "finance.overdue": "Vencido",
    "finance.total": "Total",
    "finance.subtotal": "Subtotal",
    "finance.tax": "Impuesto",
    "finance.noInvoices": "Sin facturas",
    "finance.noExpenses": "Sin gastos",

    // ── Travel ────────────────────────────────────────────────────────────────
    "travel.destination": "Destino",
    "travel.departure": "Salida",
    "travel.return": "Regreso",
    "travel.status": "Estado",
    "travel.expenses": "Gastos de viaje",
    "travel.advance": "Anticipo",
    "travel.settlement": "Liquidación",
    "travel.noTravel": "Sin viajes registrados",
    "travel.newTravel": "Nuevo viaje",

    // ── Tracker ───────────────────────────────────────────────────────────────
    "tracker.start": "Iniciar jornada",
    "tracker.pause": "Pausar",
    "tracker.resume": "Reanudar",
    "tracker.stop": "Detener",
    "tracker.elapsed": "Tiempo transcurrido",
    "tracker.notes": "Notas de jornada",
    "tracker.noSessions": "Sin sesiones registradas",

    // ── Disputes ──────────────────────────────────────────────────────────────
    "dispute.reason": "Motivo",
    "dispute.open": "Abrir disputa",
    "dispute.resolve": "Resolver",
    "dispute.noDisputes": "Sin disputas",
    "dispute.status.open": "Abierta",
    "dispute.status.resolved": "Resuelta",
    "dispute.status.assigned": "Asignada",

    // ── Compliance ────────────────────────────────────────────────────────────
    "compliance.status.compliant": "Cumple",
    "compliance.status.warning": "Alerta",
    "compliance.status.violation": "Violación",
    "compliance.status.pending": "Pendiente",
    "compliance.category.legal": "Legal",
    "compliance.category.license": "Licencia",
    "compliance.category.insurance": "Seguro",
    "compliance.category.escrow": "Escrow",
    "compliance.category.data": "Datos",

    // ── Users ─────────────────────────────────────────────────────────────────
    "users.role.admin": "Administrador",
    "users.role.worker": "Profesional",
    "users.role.client": "Cliente",
    "users.status.active": "Activo",
    "users.status.suspended": "Suspendido",
    "users.noUsers": "Sin usuarios",
    "users.invite": "Invitar usuario",
    "users.verify": "Verificar",
    "users.suspend": "Suspender",

    // ── Settings ──────────────────────────────────────────────────────────────
    "settings.general": "General",
    "settings.notifications": "Notificaciones",
    "settings.security": "Seguridad",
    "settings.integrations": "Integraciones",
    "settings.language": "Idioma de la plataforma",
    "settings.theme": "Tema visual",
    "settings.aiTone": "Tono del asistente IA",
    "settings.aiVerbosity": "Nivel de detalle",

    // ── Escrow ────────────────────────────────────────────────────────────────
    "escrow.fund": "Fondear escrow",
    "escrow.release": "Liberar fondos",
    "escrow.status": "Estado del escrow",
    "escrow.available": "Disponible",
    "escrow.total": "Total fondeado",
    "escrow.released": "Liberado",
    "escrow.noEscrow": "Sin escrow configurado",

    // ── BuildOps ──────────────────────────────────────────────────────────────
    "buildops.project": "Proyecto",
    "buildops.projects": "Proyectos",
    "buildops.task": "Tarea",
    "buildops.tasks": "Tareas",
    "buildops.milestone": "Hito",
    "buildops.milestones": "Hitos",
    "buildops.status.open": "Abierto",
    "buildops.status.in_progress": "En progreso",
    "buildops.status.blocked": "Bloqueado",
    "buildops.status.completed": "Completado",
    "buildops.status.cancelled": "Cancelado",
    "buildops.projectStatus.estimating": "Estimando",
    "buildops.projectStatus.quoted": "Cotizado",
    "buildops.taskStatus.todo": "Por hacer",
    "buildops.taskStatus.done": "Hecha",
    "buildops.taskStatus.canceled": "Cancelada",
    "buildops.milestoneStatus.awaitingReview": "Esperando revisión",
    "buildops.newProject": "Nuevo proyecto",
    "buildops.newTask": "Nueva tarea",
    "buildops.noProjects": "Sin proyectos",
    "buildops.noTasks": "Sin tareas",
    "buildops.activeProjects": "Proyectos activos",
    "buildops.draftEstimates": "Estimados borrador",
    "buildops.tasksDue": "Tareas por vencer",
    "buildops.milestonesPending": "Hitos pendientes",
    "buildops.evidencePending": "Evidencia pendiente",
    "buildops.riskAlerts": "Alertas de riesgo",
    "buildops.jobsInProgressHint": "Trabajos en ejecución",
    "buildops.toolResultsHint": "Resultados de tools listos para guardar",
    "buildops.todayNext24hHint": "Hoy y próximas 24h",
    "buildops.awaitingApprovalHint": "Esperando aprobación",
    "buildops.uploadDocsHint": "Fotos y documentos por subir",
    "buildops.needsReviewHint": "Requiere revisión",
    "buildops.workbenchDesc": "Los resultados de tools se convierten en estimados, proyectos, tareas, hitos, evidencia y reportes. Este módulo es la mesa de trabajo de ejecución.",
    "buildops.loadingOverview": "Cargando BuildOps...",
    "buildops.recentActivity": "Actividad reciente",
    "buildops.latestEvents": "Últimos eventos de BuildOps desde tools y trabajo de campo.",
    "buildops.reviewMilestones": "Revisar hitos",
    "buildops.openToolsHub": "Abrir hub de tools",
    "buildops.reviewOperations": "Revisar operaciones",
    "buildops.loadingProjects": "Cargando proyectos...",
    "buildops.noProjectsYet": "Aún no hay proyectos",
    "buildops.noProjectsHint": "Crea uno desde el resultado de una tool o inicia un proyecto BuildOps desde cero.",
    "buildops.risk": "Riesgo",
    "buildops.noBudget": "Sin presupuesto",
    "buildops.openProject": "Abrir proyecto",
    "buildops.projectDetailIntro": "Vista de detalle del proyecto. Después conectaremos tareas, evidencia y reportes.",
    "buildops.riskScore": "Puntaje de riesgo",
    "buildops.projectSummary": "Resumen del proyecto",
    "buildops.client": "Cliente",
    "buildops.professional": "Profesional",
    "buildops.sourceTool": "Tool origen",
    "buildops.manualSource": "manual",
    "buildops.projectId": "ID del proyecto",
    "buildops.complete": "completado",
    "buildops.fromToolResult": "Desde resultado de tool",
    "buildops.manualProject": "Proyecto manual",
    "buildops.createTask": "Crear tarea",
    "buildops.addEvidence": "Agregar evidencia",
    "buildops.approveMilestone": "Aprobar hito",
    "buildops.messageTeam": "Escribir al equipo",
    "buildops.planApproval": "Aprobación del plan",
    "buildops.planApprovalStatus": "Estado de aprobación",
    "buildops.planApprovalStatus.pending": "Pendiente de aprobación",
    "buildops.planApprovalStatus.approved": "Aprobado",
    "buildops.planApprovalStatus.changes_requested": "Cambios solicitados",
    "buildops.planApprovalStatus.rejected": "Rechazado",
    "buildops.approvePlan": "Aprobar plan",
    "buildops.requestPlanChanges": "Solicitar cambios",
    "buildops.rejectPlan": "Rechazar plan",
    "buildops.unapprovePlan": "Revocar aprobación",
    "buildops.approveReasonLabel": "Razón (opcional)",
    "buildops.requestChangesCommentLabel": "Cambios necesarios...",
    "buildops.rejectReasonLabel": "Motivo de rechazo",
    "buildops.unapproveReasonLabel": "Motivo de revocación",
    "buildops.approvedByLabel": "Aprobado por",
    "buildops.approvedAtLabel": "Fecha de aprobación",
    "buildops.reviewCommentLabel": "Comentario de revisión",
    "buildops.approvalSourceClient": "Cliente",
    "buildops.approvalSourceAdmin": "Admin (override)",
    "buildops.approvingPlan": "Aprobando...",
    "buildops.rejectingPlan": "Rechazando...",
    "buildops.requestingChanges": "Enviando...",
    "buildops.unapprovingPlan": "Revocando...",
    "buildops.loadingProject": "Cargando proyecto...",
    "buildops.loadingTasks": "Cargando tareas...",
    "buildops.taskLayerDesc": "Capa de tareas para la ejecución en campo. Vincula tareas con proyectos, asigna responsables y sigue fechas límite.",
    "buildops.openCount": "Abiertas",
    "buildops.doneCount": "Hechas",
    "buildops.noTasksYet": "Aún no hay tareas",
    "buildops.noTasksHint": "Crea una tarea de BuildOps para coordinar ejecución, vencimientos y responsables.",
    "buildops.noDescription": "Sin descripción",
    "buildops.unassigned": "Sin asignar",
    "buildops.due": "Vence",
    "buildops.openTask": "Abrir tarea",
    "buildops.taskDetailIntro": "Vista de detalle de la tarea. Después conectaremos evidencia, bitácora y vínculo con hitos.",
    "buildops.taskSummary": "Resumen de la tarea",
    "buildops.assignee": "Responsable",
    "buildops.taskId": "ID de la tarea",
    "buildops.followUpTask": "Nueva tarea de seguimiento",
    "buildops.openProjects": "Abrir proyectos",
    "buildops.loadingTask": "Cargando tarea...",
    "buildops.milestoneLayerDesc": "Hitos del proyecto con conteo de evidencia. Esta vista hace visible el flujo de liberación sobre la tabla de hitos existente.",
    "buildops.pending": "Pendientes",
    "buildops.approved": "Aprobados",
    "buildops.paid": "Pagados",
    "buildops.loadingMilestones": "Cargando hitos...",
    "buildops.noMilestonesYet": "Aún no hay hitos",
    "buildops.noMilestonesHint": "Crea proyectos e hitos desde el flujo central de trabajos; BuildOps los mostrará aquí cuando existan.",
    "buildops.evidenceCount": "evidencias",
    "buildops.notApproved": "Sin aprobar",
    "buildops.sequence": "Secuencia",
    "buildops.newProjectIntro": "Guarda un proyecto BuildOps o una base de estimado en Prisma.",
    "buildops.backToProjects": "Volver a proyectos",
    "buildops.backToTasks": "Volver a tareas",
    "buildops.title": "Título",
    "buildops.trade": "Especialidad",
    "buildops.clientName": "Nombre del cliente",
    "buildops.professionalName": "Nombre del profesional",
    "buildops.budgetEstimate": "Presupuesto estimado",
    "buildops.projectType": "Tipo de proyecto",
    "buildops.startDate": "Fecha de inicio",
    "buildops.dueDate": "Fecha de entrega",
    "buildops.description": "Descripción",
    "buildops.savedProjectPrisma": "Se guarda en Prisma como proyecto BuildOps.",
    "buildops.saveProject": "Guardar proyecto",
    "buildops.savingProject": "Guardando...",
    "buildops.newTaskIntro": "Crea una tarea BuildOps para ejecución, vencimientos, asignación y seguimiento del proyecto.",
    "buildops.projectContext": "Contexto de proyecto",
    "buildops.projectIdLabel": "ID del proyecto",
    "buildops.assigneeName": "Nombre del responsable",
    "buildops.assigneeUserId": "ID del usuario responsable",
    "buildops.statusLabel": "Estado",
    "buildops.priority": "Prioridad",
    "buildops.sourceToolLabel": "Tool origen",
    "buildops.savedTaskPrisma": "Se guarda en Prisma como tarea BuildOps.",
    "buildops.saveTask": "Guardar tarea",
    "buildops.savingTask": "Guardando...",
    "buildops.trade.roofing": "Techos",
    "buildops.trade.concrete": "Concreto",
    "buildops.trade.plumbing": "Plomería",
    "buildops.trade.hvac": "HVAC",
    "buildops.trade.electrical": "Electricidad",
    "buildops.trade.painting": "Pintura",
    "buildops.trade.drywall": "Drywall",
    "buildops.trade.flooring": "Pisos",
    "buildops.trade.carpentry": "Carpintería",
    "buildops.trade.tile": "Azulejo",
    "buildops.trade.windows-doors": "Ventanas / Puertas",
    "buildops.trade.insulation": "Aislamiento",
    "buildops.trade.demolition": "Demolición",
    "buildops.trade.masonry": "Mampostería",
    "buildops.projectType.remodel": "Remodelación",
    "buildops.projectType.newConstruction": "Obra nueva",
    "buildops.projectType.repair": "Reparación",
    "buildops.projectType.service": "Servicio",
    "priority.low": "Baja",
    "priority.medium": "Media",
    "priority.high": "Alta",
    "priority.urgent": "Urgente",
    "risk.low": "Bajo",
    "risk.medium": "Medio",
    "risk.high": "Alto",
    "risk.critical": "Crítico",

    // ── Agents ────────────────────────────────────────────────────────────────
    "agents.run": "Ejecución",
    "agents.status.running": "Ejecutando",
    "agents.status.completed": "Completado",
    "agents.status.failed": "Fallido",
    "agents.status.queued": "En cola",
    "agents.noRuns": "Sin ejecuciones",
    "agents.approve": "Aprobar acción",
    "agents.reject": "Rechazar acción",

    // ── Common patterns ───────────────────────────────────────────────────────
    "common.viewAll": "Ver todos",
    "common.backToDashboard": "← Dashboard",
    "common.noConnection": "Sin conexión con el servidor",
    "common.tryAgain": "Intentar de nuevo",
    "common.serverError": "Error del servidor",
    "common.notFound": "No encontrado",
    "common.unauthorized": "No autorizado",
    "common.forbidden": "Acceso denegado",
    "common.createdAt": "Creado",
    "common.updatedAt": "Actualizado",
    "common.by": "por",
    "common.of": "de",
    "common.and": "y",
    "common.or": "o",
    "common.in": "en",
    "common.at": "a las",
  },

  en: {
    // ── Roles ─────────────────────────────────────────────────────────────────
    "role.worker": "Worker",
    "role.client": "Client",
    "role.admin": "Admin",

    // ── Nav items ─────────────────────────────────────────────────────────────
    "nav.dashboard": "Dashboard",
    "nav.operations": "Operations",
    "nav.autonomy": "Autonomy",
    "nav.developerRuntime": "Developer Runtime",
    "nav.communications": "Communications",
    "nav.domainEvents": "Domain Events",
    "nav.users": "Users",
    "nav.disputes": "Disputes",
    "nav.qaCenter": "QA Center",
    "nav.compliance": "Compliance",
    "nav.finance": "Finance",
    "nav.travelOps": "Travel Ops",
    "nav.reports": "Reports",
    "nav.fieldOps": "Field Ops",
    "nav.settings": "Settings",
    "nav.htmlCanvas": "HTML Canvas",
    "nav.buildOps": "BuildOps",
    "nav.semseTools": "SEMSE Tools",
    "nav.agents": "Agents",
    "nav.coordinator": "Coordinator",
    "nav.llmMetrics": "LLM Metrics",
    "nav.missionControl": "Mission Control",
    "nav.algorithmEngine": "Algorithm Engine",
    "nav.aiMissionControl": "IA Mission Control",
    "nav.contractors": "Contractors / CRM",
    "nav.worker": "Worker / Jobs",
    "nav.consciousness": "Consciousness",
    "nav.pmo": "PMO Dashboard",
    "nav.semseX": "SEMSE_X",
    "nav.agentMemory": "Agent Memory",
    "nav.prometeo": "Prometeo RAG",
    "nav.workerDashboard": "Dashboard",
    "nav.agenda": "Agenda",
    "nav.myJobs": "My jobs",
    "nav.tasks": "Tasks",
    "nav.timeTracker": "Time Tracker",
    "nav.evidence": "Evidence",
    "nav.materials": "Materials",
    "nav.incidents": "Incidents",
    "nav.payments": "Payments",
    "nav.travel": "Travel Ops",
    "nav.myProfile": "My profile",
    "nav.aiSettings": "AI Settings",
    "nav.leads": "Leads & Clients",
    "nav.postJob": "Post job",
    "nav.myProjects": "My projects",
    "nav.aiCopilot": "AI Copilot",
    "nav.milestones": "Milestones",
    "nav.professionals": "Professionals",
    "nav.documents": "Documents",
    "nav.reviews": "Reviews",
    "nav.financeHub": "Finance Hub",

    // ── Sections ──────────────────────────────────────────────────────────────
    "section.main": "Main",
    "section.control": "Control",
    "section.operations": "Operations",
    "section.field": "Field",
    "section.ai": "AI",
    "section.lab": "Lab",

    // ── Common UI ─────────────────────────────────────────────────────────────
    "ui.signOut": "Sign out",
    "ui.language": "Language",
    "ui.theme": "Theme",
    "ui.dark": "Dark",
    "ui.light": "Light",
    "ui.notifications": "Notifications",
    "ui.loading": "Loading…",
    "ui.save": "Save",
    "ui.cancel": "Cancel",
    "ui.back": "Back",
    "ui.new": "New",
    "ui.edit": "Edit",
    "ui.delete": "Delete",
    "ui.search": "Search",
    "ui.filter": "Filter",
    "ui.export": "Export",
    "ui.import": "Import",
    "ui.refresh": "Refresh",
    "ui.view": "View",
    "ui.add": "Add",
    "ui.create": "Create",
    "ui.update": "Update",
    "ui.confirm": "Confirm",
    "ui.submit": "Submit",
    "ui.approve": "Approve",
    "ui.reject": "Reject",
    "ui.resolve": "Resolve",
    "ui.open": "Open",
    "ui.close": "Close",
    "ui.download": "Download",
    "ui.upload": "Upload",
    "ui.send": "Send",
    "ui.retry": "Retry",
    "ui.details": "Details",
    "ui.actions": "Actions",
    "ui.status": "Status",
    "ui.date": "Date",
    "ui.amount": "Amount",
    "ui.total": "Total",
    "ui.name": "Name",
    "ui.description": "Description",
    "ui.type": "Type",
    "ui.role": "Role",
    "ui.email": "Email",
    "ui.noData": "No data available",
    "ui.noResults": "No results",
    "ui.error": "Error",
    "ui.success": "Success",
    "ui.warning": "Warning",
    "ui.info": "Info",
    "ui.optional": "Optional",
    "ui.required": "Required",
    "ui.all": "All",
    "ui.none": "None",
    "ui.yes": "Yes",
    "ui.no": "No",
    "ui.active": "Active",
    "ui.inactive": "Inactive",
    "ui.enabled": "Enabled",
    "ui.disabled": "Disabled",
    "ui.online": "Online",
    "ui.offline": "Offline",
    "ui.pending": "Pending",
    "ui.completed": "Completed",
    "ui.failed": "Failed",
    "ui.cancelled": "Cancelled",
    "ui.more": "More",
    "ui.less": "Less",
    "ui.showMore": "Show more",
    "ui.showLess": "Show less",
    "ui.seeAll": "See all",
    "ui.back_to": "Back to",
    "ui.since": "",
    "ui.ago": "ago",

    // ── Job status ────────────────────────────────────────────────────────────
    "status.draft": "Draft",
    "status.posted": "Posted",
    "status.reserved": "Reserved",
    "status.accepted": "Accepted",
    "status.in_progress": "In progress",
    "status.review": "In review",
    "status.dispute": "In dispute",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
    "status.open": "Open",
    "status.closed": "Closed",
    "status.resolved": "Resolved",
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.submitted": "Submitted",
    "status.funded": "Funded",
    "status.released": "Released",
    "status.running": "Running",
    "status.paused": "Paused",
    "status.stopped": "Stopped",
    "status.failed": "Failed",
    "status.queued": "Queued",

    // ── Pages — Admin ─────────────────────────────────────────────────────────
    "page.adminDashboard": "Admin dashboard",
    "page.adminDashboard.sub": "SEMSE operations overview",
    "page.operations": "Operations",
    "page.operations.sub": "Agent monitor and domain events",
    "page.autonomy": "Autonomy",
    "page.autonomy.sub": "Agentic autonomy engine",
    "page.developerRuntime": "Developer Runtime",
    "page.developerRuntime.sub": "Developer execution sessions",
    "page.compliance": "Compliance",
    "page.compliance.sub": "Contract and license audit",
    "page.qaCenter": "QA Center",
    "page.qaCenter.sub": "Quality control and validations",
    "page.disputes": "Disputes",
    "page.disputes.sub": "Conflict management between parties",
    "page.users": "Users",
    "page.users.sub": "Profile and role management",
    "page.finance": "Finance",
    "page.finance.sub": "Invoices, expenses and financial summary",
    "page.reports": "Reports",
    "page.reports.sub": "Platform analytics and metrics",
    "page.settings": "Settings",
    "page.settings.sub": "SEMSE OS system settings",
    "page.fieldOps": "Field Operations",
    "page.fieldOps.sub": "Work units and on-site management",
    "page.travelOps": "Travel Ops",
    "page.travelOps.sub": "Travel and expense management",
    "page.domainEvents": "Domain Events",
    "page.domainEvents.sub": "System event traceability",
    "page.llmMetrics": "LLM Metrics",
    "page.llmMetrics.sub": "Language model performance",
    "page.aiMissionControl": "AI Mission Control",
    "page.aiMissionControl.sub": "AI agents command center",
    "page.coordinator": "Coordinator",
    "page.coordinator.sub": "Operations coordinator agent",
    "page.pmo": "PMO Dashboard",
    "page.pmo.sub": "AI-assisted project management",
    "page.agentMemory": "Agent Memory",
    "page.agentMemory.sub": "Agentic context storage and retrieval",
    "page.prometeo": "Prometeo RAG",
    "page.prometeo.sub": "Knowledge base and semantic retrieval",

    // ── Pages — Worker ────────────────────────────────────────────────────────
    "page.workerDashboard": "My dashboard",
    "page.workerDashboard.sub": "Work summary and daily activity",
    "page.myJobs": "My jobs",
    "page.myJobs.sub": "Assigned and active jobs",
    "page.timeTracker": "Time tracker",
    "page.timeTracker.sub": "Work sessions and hours log",
    "page.evidence": "Evidence",
    "page.evidence.sub": "Photos, documents and site files",
    "page.materials": "Materials",
    "page.materials.sub": "Material requests and tracking",
    "page.incidents": "Incidents",
    "page.incidents.sub": "Field issue reporting",
    "page.workerPayments": "My payments",
    "page.workerPayments.sub": "Escrow and payment releases",
    "page.workerTravel": "Travel",
    "page.workerTravel.sub": "Travel and expense management",
    "page.workerFieldOps": "Field Operations",
    "page.workerFieldOps.sub": "Work units and on-site logging",
    "page.agenda": "Agenda",
    "page.agenda.sub": "Job calendar and appointments",
    "page.tasks": "My tasks",
    "page.tasks.sub": "Assigned task list",
    "page.profile": "My profile",
    "page.profile.sub": "Personal info and account settings",
    "page.aiAssistant": "AI Assistant",
    "page.aiAssistant.sub": "Intelligent assistant preferences",

    // ── Pages — Client ────────────────────────────────────────────────────────
    "page.clientDashboard": "My dashboard",
    "page.clientDashboard.sub": "Project summary and activity",
    "page.postJob": "Post a job",
    "page.postJob.sub": "Create a new service request",
    "page.myProjects": "My projects",
    "page.myProjects.sub": "Active jobs and AI copilot",
    "page.clientMilestones": "My milestones",
    "page.clientMilestones.sub": "Progress tracking and approvals",
    "page.clientPayments": "Payments",
    "page.clientPayments.sub": "Transaction history and escrow",
    "page.clientDisputes": "Disputes",
    "page.clientDisputes.sub": "Conflicts and resolutions",
    "page.clientDocuments": "Documents",
    "page.clientDocuments.sub": "Contracts, reports and files",
    "page.clientFinance": "Finance",
    "page.clientFinance.sub": "Invoices and financial status",
    "page.professionals": "Professionals",
    "page.professionals.sub": "Verified provider directory",
    "page.reviews": "Reviews",
    "page.reviews.sub": "Job ratings and comments",
    "page.leads": "Leads & Clients",
    "page.leads.sub": "Prospect and client pipeline",

    // ── Pages — BuildOps ──────────────────────────────────────────────────────
    "page.buildOps": "BuildOps",
    "page.buildOps.sub": "Construction project management",
    "page.buildOpsProjects": "Projects",
    "page.buildOpsProjects.sub": "Active project list",
    "page.buildOpsMilestones": "Project milestones",
    "page.buildOpsMilestones.sub": "Stage progress tracking",
    "page.buildOpsTasks": "Tasks",
    "page.buildOpsTasks.sub": "Project task list",

    // ── Pages — Tools ─────────────────────────────────────────────────────────
    "page.tools": "SEMSE Tools",
    "page.tools.sub": "Professional calculators by specialty",
    "page.toolsDashboard": "Tools dashboard",
    "page.toolsDashboard.sub": "Access all estimation engines",

    // ── Dashboard strings ─────────────────────────────────────────────────────
    "dash.quickActions": "Quick actions",
    "dash.fastManagement": "Quick management",
    "dash.fieldOpsDesc": "Go to units and field work",
    "dash.recentActivity": "Recent activity",
    "dash.summary": "Summary",
    "dash.metrics": "Metrics",
    "dash.alerts": "Alerts",
    "dash.noAlerts": "No active alerts",
    "dash.lastRefresh": "Last updated",
    "dash.totalJobs": "Total jobs",
    "dash.activeJobs": "Active jobs",
    "dash.completedJobs": "Completed jobs",
    "dash.totalUsers": "Total users",
    "dash.openDisputes": "Open disputes",
    "dash.revenue": "Revenue",

    // ── Operations ────────────────────────────────────────────────────────────
    "ops.agentRuns": "Agent runs",
    "ops.pendingApprovals": "Pending approvals",
    "ops.requeue": "Requeue",
    "ops.retry": "Retry",
    "ops.approve": "Approve",
    "ops.reject": "Reject",
    "ops.openIncident": "Open incident",
    "ops.runStatus": "Run status",
    "ops.agentType": "Agent type",
    "ops.noRuns": "No recent runs",
    "ops.noApprovals": "No pending approvals",

    // ── Jobs ──────────────────────────────────────────────────────────────────
    "job.title": "Title",
    "job.budget": "Budget",
    "job.status": "Status",
    "job.client": "Client",
    "job.worker": "Worker",
    "job.created": "Created",
    "job.updated": "Updated",
    "job.noJobs": "No jobs available",
    "job.newJob": "New job",
    "job.viewJob": "View job",
    "job.postJob": "Post job",
    "job.scope": "Scope",
    "job.location": "Location",

    // ── Milestones ────────────────────────────────────────────────────────────
    "milestone.title": "Milestone name",
    "milestone.amount": "Amount",
    "milestone.status": "Status",
    "milestone.sequence": "Sequence",
    "milestone.submit": "Submit",
    "milestone.approve": "Approve",
    "milestone.reject": "Reject",
    "milestone.release": "Release payment",
    "milestone.noMilestones": "No milestones created",
    "milestone.create": "Create milestone",

    // ── Evidence ──────────────────────────────────────────────────────────────
    "evidence.kind": "Evidence type",
    "evidence.filename": "File name",
    "evidence.upload": "Upload evidence",
    "evidence.register": "Register evidence",
    "evidence.noEvidence": "No evidence registered",
    "evidence.photo": "Photo",
    "evidence.document": "Document",
    "evidence.video": "Video",

    // ── Finance ───────────────────────────────────────────────────────────────
    "finance.invoice": "Invoice",
    "finance.invoices": "Invoices",
    "finance.expense": "Expense",
    "finance.expenses": "Expenses",
    "finance.amount": "Amount",
    "finance.paid": "Paid",
    "finance.unpaid": "Unpaid",
    "finance.overdue": "Overdue",
    "finance.total": "Total",
    "finance.subtotal": "Subtotal",
    "finance.tax": "Tax",
    "finance.noInvoices": "No invoices",
    "finance.noExpenses": "No expenses",

    // ── Travel ────────────────────────────────────────────────────────────────
    "travel.destination": "Destination",
    "travel.departure": "Departure",
    "travel.return": "Return",
    "travel.status": "Status",
    "travel.expenses": "Travel expenses",
    "travel.advance": "Advance",
    "travel.settlement": "Settlement",
    "travel.noTravel": "No travel records",
    "travel.newTravel": "New travel",

    // ── Tracker ───────────────────────────────────────────────────────────────
    "tracker.start": "Start session",
    "tracker.pause": "Pause",
    "tracker.resume": "Resume",
    "tracker.stop": "Stop",
    "tracker.elapsed": "Time elapsed",
    "tracker.notes": "Session notes",
    "tracker.noSessions": "No sessions recorded",

    // ── Disputes ──────────────────────────────────────────────────────────────
    "dispute.reason": "Reason",
    "dispute.open": "Open dispute",
    "dispute.resolve": "Resolve",
    "dispute.noDisputes": "No disputes",
    "dispute.status.open": "Open",
    "dispute.status.resolved": "Resolved",
    "dispute.status.assigned": "Assigned",

    // ── Compliance ────────────────────────────────────────────────────────────
    "compliance.status.compliant": "Compliant",
    "compliance.status.warning": "Warning",
    "compliance.status.violation": "Violation",
    "compliance.status.pending": "Pending",
    "compliance.category.legal": "Legal",
    "compliance.category.license": "License",
    "compliance.category.insurance": "Insurance",
    "compliance.category.escrow": "Escrow",
    "compliance.category.data": "Data",

    // ── Users ─────────────────────────────────────────────────────────────────
    "users.role.admin": "Administrator",
    "users.role.worker": "Worker",
    "users.role.client": "Client",
    "users.status.active": "Active",
    "users.status.suspended": "Suspended",
    "users.noUsers": "No users",
    "users.invite": "Invite user",
    "users.verify": "Verify",
    "users.suspend": "Suspend",

    // ── Settings ──────────────────────────────────────────────────────────────
    "settings.general": "General",
    "settings.notifications": "Notifications",
    "settings.security": "Security",
    "settings.integrations": "Integrations",
    "settings.language": "Platform language",
    "settings.theme": "Visual theme",
    "settings.aiTone": "AI assistant tone",
    "settings.aiVerbosity": "Detail level",

    // ── Escrow ────────────────────────────────────────────────────────────────
    "escrow.fund": "Fund escrow",
    "escrow.release": "Release funds",
    "escrow.status": "Escrow status",
    "escrow.available": "Available",
    "escrow.total": "Total funded",
    "escrow.released": "Released",
    "escrow.noEscrow": "No escrow configured",

    // ── BuildOps ──────────────────────────────────────────────────────────────
    "buildops.project": "Project",
    "buildops.projects": "Projects",
    "buildops.task": "Task",
    "buildops.tasks": "Tasks",
    "buildops.milestone": "Milestone",
    "buildops.milestones": "Milestones",
    "buildops.status.open": "Open",
    "buildops.status.in_progress": "In progress",
    "buildops.status.blocked": "Blocked",
    "buildops.status.completed": "Completed",
    "buildops.status.cancelled": "Cancelled",
    "buildops.projectStatus.estimating": "Estimating",
    "buildops.projectStatus.quoted": "Quoted",
    "buildops.taskStatus.todo": "To do",
    "buildops.taskStatus.done": "Done",
    "buildops.taskStatus.canceled": "Canceled",
    "buildops.milestoneStatus.awaitingReview": "Awaiting review",
    "buildops.newProject": "New project",
    "buildops.newTask": "New task",
    "buildops.noProjects": "No projects",
    "buildops.noTasks": "No tasks",
    "buildops.activeProjects": "Active projects",
    "buildops.draftEstimates": "Draft estimates",
    "buildops.tasksDue": "Tasks due",
    "buildops.milestonesPending": "Pending milestones",
    "buildops.evidencePending": "Pending evidence",
    "buildops.riskAlerts": "Risk alerts",
    "buildops.jobsInProgressHint": "Jobs in progress",
    "buildops.toolResultsHint": "Tool results ready to save",
    "buildops.todayNext24hHint": "Today and next 24h",
    "buildops.awaitingApprovalHint": "Awaiting approval",
    "buildops.uploadDocsHint": "Photos and documents to upload",
    "buildops.needsReviewHint": "Needs review",
    "buildops.workbenchDesc": "Tool results become estimates, projects, tasks, milestones, evidence and reports. This module is the execution workbench.",
    "buildops.loadingOverview": "Loading BuildOps...",
    "buildops.recentActivity": "Recent activity",
    "buildops.latestEvents": "Latest BuildOps events from tools and field work.",
    "buildops.reviewMilestones": "Review milestones",
    "buildops.openToolsHub": "Open tools hub",
    "buildops.reviewOperations": "Review operations",
    "buildops.loadingProjects": "Loading projects...",
    "buildops.noProjectsYet": "No projects yet",
    "buildops.noProjectsHint": "Create one from a tool result or start a BuildOps project from scratch.",
    "buildops.risk": "Risk",
    "buildops.noBudget": "No budget",
    "buildops.openProject": "Open project",
    "buildops.projectDetailIntro": "Project detail view. Later this will connect to tasks, evidence and reports.",
    "buildops.riskScore": "Risk score",
    "buildops.projectSummary": "Project summary",
    "buildops.client": "Client",
    "buildops.professional": "Professional",
    "buildops.sourceTool": "Source tool",
    "buildops.manualSource": "manual",
    "buildops.projectId": "Project ID",
    "buildops.complete": "complete",
    "buildops.fromToolResult": "From tool result",
    "buildops.manualProject": "Manual project",
    "buildops.createTask": "Create task",
    "buildops.addEvidence": "Add evidence",
    "buildops.approveMilestone": "Approve milestone",
    "buildops.messageTeam": "Message team",
    "buildops.planApproval": "Plan Approval",
    "buildops.planApprovalStatus": "Approval Status",
    "buildops.planApprovalStatus.pending": "Pending Approval",
    "buildops.planApprovalStatus.approved": "Approved",
    "buildops.planApprovalStatus.changes_requested": "Changes Requested",
    "buildops.planApprovalStatus.rejected": "Rejected",
    "buildops.approvePlan": "Approve Plan",
    "buildops.requestPlanChanges": "Request Changes",
    "buildops.rejectPlan": "Reject Plan",
    "buildops.unapprovePlan": "Revoke Approval",
    "buildops.approveReasonLabel": "Reason (optional)",
    "buildops.requestChangesCommentLabel": "Changes needed...",
    "buildops.rejectReasonLabel": "Rejection reason",
    "buildops.unapproveReasonLabel": "Reason for revoking",
    "buildops.approvedByLabel": "Approved by",
    "buildops.approvedAtLabel": "Approved on",
    "buildops.reviewCommentLabel": "Review comment",
    "buildops.approvalSourceClient": "Client",
    "buildops.approvalSourceAdmin": "Admin (override)",
    "buildops.approvingPlan": "Approving...",
    "buildops.rejectingPlan": "Rejecting...",
    "buildops.requestingChanges": "Sending...",
    "buildops.unapprovingPlan": "Revoking...",
    "buildops.loadingProject": "Loading project...",
    "buildops.loadingTasks": "Loading tasks...",
    "buildops.taskLayerDesc": "Task layer for field execution. Link tasks to projects, assign owners and track due dates.",
    "buildops.openCount": "Open",
    "buildops.doneCount": "Done",
    "buildops.noTasksYet": "No tasks yet",
    "buildops.noTasksHint": "Create a BuildOps task to coordinate execution, due dates and accountability.",
    "buildops.noDescription": "No description",
    "buildops.unassigned": "Unassigned",
    "buildops.due": "Due",
    "buildops.openTask": "Open task",
    "buildops.taskDetailIntro": "Task detail view. Later this will connect to evidence, logs and milestone linkage.",
    "buildops.taskSummary": "Task summary",
    "buildops.assignee": "Assignee",
    "buildops.taskId": "Task ID",
    "buildops.followUpTask": "New follow-up task",
    "buildops.openProjects": "Open projects",
    "buildops.loadingTask": "Loading task...",
    "buildops.milestoneLayerDesc": "Project milestones with evidence counts. This view keeps the release flow visible on top of the existing milestone table.",
    "buildops.pending": "Pending",
    "buildops.approved": "Approved",
    "buildops.paid": "Paid",
    "buildops.loadingMilestones": "Loading milestones...",
    "buildops.noMilestonesYet": "No milestones yet",
    "buildops.noMilestonesHint": "Create projects and milestones from the core job flow; BuildOps will show them here once they exist.",
    "buildops.evidenceCount": "evidence",
    "buildops.notApproved": "Not approved",
    "buildops.sequence": "Sequence",
    "buildops.newProjectIntro": "Save a BuildOps project or an estimate shell into Prisma.",
    "buildops.backToProjects": "Back to projects",
    "buildops.backToTasks": "Back to tasks",
    "buildops.title": "Title",
    "buildops.trade": "Trade",
    "buildops.clientName": "Client name",
    "buildops.professionalName": "Professional name",
    "buildops.budgetEstimate": "Budget estimate",
    "buildops.projectType": "Project type",
    "buildops.startDate": "Start date",
    "buildops.dueDate": "Due date",
    "buildops.description": "Description",
    "buildops.savedProjectPrisma": "Saved to Prisma as a BuildOps project.",
    "buildops.saveProject": "Save project",
    "buildops.savingProject": "Saving...",
    "buildops.newTaskIntro": "Create a BuildOps task for execution, due dates, assignment and project tracking.",
    "buildops.projectContext": "Project context",
    "buildops.projectIdLabel": "Project ID",
    "buildops.assigneeName": "Assignee name",
    "buildops.assigneeUserId": "Assignee user ID",
    "buildops.statusLabel": "Status",
    "buildops.priority": "Priority",
    "buildops.sourceToolLabel": "Source tool",
    "buildops.savedTaskPrisma": "Saved to Prisma as a BuildOps task.",
    "buildops.saveTask": "Save task",
    "buildops.savingTask": "Saving...",
    "buildops.trade.roofing": "Roofing",
    "buildops.trade.concrete": "Concrete",
    "buildops.trade.plumbing": "Plumbing",
    "buildops.trade.hvac": "HVAC",
    "buildops.trade.electrical": "Electrical",
    "buildops.trade.painting": "Painting",
    "buildops.trade.drywall": "Drywall",
    "buildops.trade.flooring": "Flooring",
    "buildops.trade.carpentry": "Carpentry",
    "buildops.trade.tile": "Tile",
    "buildops.trade.windows-doors": "Windows / Doors",
    "buildops.trade.insulation": "Insulation",
    "buildops.trade.demolition": "Demolition",
    "buildops.trade.masonry": "Masonry",
    "buildops.projectType.remodel": "Remodel",
    "buildops.projectType.newConstruction": "New construction",
    "buildops.projectType.repair": "Repair",
    "buildops.projectType.service": "Service",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",
    "risk.low": "Low",
    "risk.medium": "Medium",
    "risk.high": "High",
    "risk.critical": "Critical",

    // ── Agents ────────────────────────────────────────────────────────────────
    "agents.run": "Run",
    "agents.status.running": "Running",
    "agents.status.completed": "Completed",
    "agents.status.failed": "Failed",
    "agents.status.queued": "Queued",
    "agents.noRuns": "No runs",
    "agents.approve": "Approve action",
    "agents.reject": "Reject action",

    // ── Common patterns ───────────────────────────────────────────────────────
    "common.viewAll": "View all",
    "common.backToDashboard": "← Dashboard",
    "common.noConnection": "Cannot connect to server",
    "common.tryAgain": "Try again",
    "common.serverError": "Server error",
    "common.notFound": "Not found",
    "common.unauthorized": "Unauthorized",
    "common.forbidden": "Access denied",
    "common.createdAt": "Created",
    "common.updatedAt": "Updated",
    "common.by": "by",
    "common.of": "of",
    "common.and": "and",
    "common.or": "or",
    "common.in": "in",
    "common.at": "at",
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  language: "es",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguagePreference>("es");

  useEffect(() => {
    const saved = window.localStorage.getItem("semse-language");
    if (saved === "es" || saved === "en") {
      setLanguageState(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  function setLanguage(lang: LanguagePreference) {
    setLanguageState(lang);
    window.localStorage.setItem("semse-language", lang);
    document.documentElement.lang = lang;
  }

  function t(key: string): string {
    return T[language][key] ?? T.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
