export type NavigationLayer = "mission-control" | "workspace" | "context";

export type NavigationOS =
  | "mission-control"
  | "client"
  | "contractor"
  | "operations"
  | "marketplace"
  | "governance"
  | "ai"
  | "system";

export interface NavigationNode {
  id: string;
  labelKey: string;
  canonicalHref: string;
  legacyHrefs?: string[];
  layer: NavigationLayer;
  os: NavigationOS;
  roles: Array<"admin" | "client" | "worker">;
  owner: string;
  entityType?: "job" | "project" | "milestone" | "evidence" | "payment" | "proposal" | "trace" | "worker";
  status: "active" | "alias" | "deprecated" | "planned";
}

export const navigationRegistry: NavigationNode[] = [
  // Mission Control
  {
    id: "mission-control",
    labelKey: "nav.missionControl",
    canonicalHref: "/admin/mission-control",
    legacyHrefs: ["/admin/dashboard"],
    layer: "mission-control",
    os: "mission-control",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "ai-mission-control",
    labelKey: "nav.aiMissionControl",
    canonicalHref: "/ai/mission-control",
    legacyHrefs: ["/admin/ai-mission-control"],
    layer: "mission-control",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },

  // Contractor OS (Worker)
  {
    id: "contractor-home",
    labelKey: "nav.workerDashboard",
    canonicalHref: "/worker/dashboard",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-agenda",
    labelKey: "nav.agenda",
    canonicalHref: "/worker/agenda",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-jobs",
    labelKey: "nav.myJobs",
    canonicalHref: "/worker/jobs",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
    entityType: "job",
  },
  {
    id: "worker-tasks",
    labelKey: "nav.tasks",
    canonicalHref: "/worker/tasks",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-tracker",
    labelKey: "nav.timeTracker",
    canonicalHref: "/worker/tracker",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-evidence",
    labelKey: "nav.evidence",
    canonicalHref: "/worker/evidence",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
    entityType: "evidence",
  },
  {
    id: "worker-materials",
    labelKey: "nav.materials",
    canonicalHref: "/worker/materials",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-incidents",
    labelKey: "nav.incidents",
    canonicalHref: "/worker/incidents",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-payments",
    labelKey: "nav.payments",
    canonicalHref: "/worker/payments",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
    entityType: "payment",
  },
  {
    id: "worker-travel",
    labelKey: "nav.travel",
    canonicalHref: "/worker/travel",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-field-ops",
    labelKey: "nav.fieldOps",
    canonicalHref: "/worker/field-ops",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-profile",
    labelKey: "nav.myProfile",
    canonicalHref: "/worker/profile",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
    entityType: "worker",
  },
  {
    id: "worker-settings",
    labelKey: "nav.aiSettings",
    canonicalHref: "/worker/settings",
    layer: "workspace",
    os: "contractor",
    roles: ["worker"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "worker-agents",
    labelKey: "nav.agents",
    canonicalHref: "/agents",
    layer: "workspace",
    os: "ai",
    roles: ["worker"],
    owner: "ai-operations",
    status: "active",
  },

  // Client OS
  {
    id: "client-home",
    labelKey: "nav.dashboard",
    canonicalHref: "/client/dashboard",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-leads",
    labelKey: "nav.leads",
    canonicalHref: "/client/leads",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-post-job",
    labelKey: "nav.postJob",
    canonicalHref: "/client/jobs/new",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
    entityType: "job",
  },
  {
    id: "client-my-projects",
    labelKey: "nav.myProjects",
    canonicalHref: "/client/jobs",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
    entityType: "project",
  },
  {
    id: "client-ai-copilot",
    labelKey: "nav.aiCopilot",
    canonicalHref: "/client/projects",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-milestones",
    labelKey: "nav.milestones",
    canonicalHref: "/client/milestones",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
    entityType: "milestone",
  },
  {
    id: "client-professionals",
    labelKey: "nav.professionals",
    canonicalHref: "/client/professionals",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-marketplace",
    labelKey: "nav.clientMarketplace",
    canonicalHref: "/client/marketplace",
    layer: "workspace",
    os: "marketplace",
    roles: ["client"],
    owner: "marketplace",
    status: "active",
  },
  {
    id: "client-bids",
    labelKey: "nav.myBids",
    canonicalHref: "/client/bids",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
    entityType: "proposal",
  },
  {
    id: "client-protools",
    labelKey: "nav.protools",
    canonicalHref: "/client/protools",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-documents",
    labelKey: "nav.documents",
    canonicalHref: "/client/documents",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-reviews",
    labelKey: "nav.reviews",
    canonicalHref: "/client/reviews",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-payments",
    labelKey: "nav.payments",
    canonicalHref: "/client/payments",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
    entityType: "payment",
  },
  {
    id: "client-finance",
    labelKey: "nav.financeHub",
    canonicalHref: "/client/finance",
    layer: "workspace",
    os: "client",
    roles: ["client"],
    owner: "client-success",
    status: "active",
  },
  {
    id: "client-agents",
    labelKey: "nav.agents",
    canonicalHref: "/agents",
    layer: "workspace",
    os: "ai",
    roles: ["client"],
    owner: "ai-operations",
    status: "active",
  },

  // Operations OS
  {
    id: "ops-monitoring",
    labelKey: "nav.operations",
    canonicalHref: "/ops/monitoring",
    legacyHrefs: ["/admin/ops"],
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "ops-buildops",
    labelKey: "nav.buildOps",
    canonicalHref: "/ops/buildops",
    legacyHrefs: ["/buildops"],
    layer: "workspace",
    os: "operations",
    roles: ["admin", "worker"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-contractors",
    labelKey: "nav.contractors",
    canonicalHref: "/admin/contractors",
    layer: "workspace",
    os: "marketplace",
    roles: ["admin"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "admin-marketplace",
    labelKey: "nav.marketplace",
    canonicalHref: "/admin/marketplace",
    layer: "workspace",
    os: "marketplace",
    roles: ["admin"],
    owner: "marketplace",
    status: "active",
  },
  {
    id: "admin-trust",
    labelKey: "nav.trust",
    canonicalHref: "/admin/trust",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-reputation",
    labelKey: "nav.reputation",
    canonicalHref: "/admin/reputation",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-worker",
    labelKey: "nav.worker",
    canonicalHref: "/admin/worker",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-autonomy",
    labelKey: "nav.autonomy",
    canonicalHref: "/admin/autonomy",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-developer-runtime",
    labelKey: "nav.developerRuntime",
    canonicalHref: "/admin/developer-runtime",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },
  {
    id: "admin-disputes",
    labelKey: "nav.disputes",
    canonicalHref: "/admin/disputes",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-vision",
    labelKey: "nav.visionAI",
    canonicalHref: "/admin/vision",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-qa",
    labelKey: "nav.qaCenter",
    canonicalHref: "/admin/qa",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-compliance",
    labelKey: "nav.compliance",
    canonicalHref: "/admin/compliance",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-finance",
    labelKey: "nav.finance",
    canonicalHref: "/admin/finance",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-travel",
    labelKey: "nav.travelOps",
    canonicalHref: "/admin/travel",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-reports",
    labelKey: "nav.reports",
    canonicalHref: "/admin/reports",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-field-ops",
    labelKey: "nav.fieldOps",
    canonicalHref: "/admin/field-ops",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "marketplace-operations",
    status: "active",
  },
  {
    id: "admin-coordinator",
    labelKey: "nav.coordinator",
    canonicalHref: "/admin/coordinator",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-consciousness",
    labelKey: "nav.consciousness",
    canonicalHref: "/admin/consciousness",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },
  {
    id: "admin-pmo",
    labelKey: "nav.pmo",
    canonicalHref: "/admin/pmo",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "active",
  },

  // Governance OS
  {
    id: "governance-proposals",
    labelKey: "nav.governance",
    canonicalHref: "/governance/proposals",
    legacyHrefs: ["/admin/governance"],
    layer: "workspace",
    os: "governance",
    roles: ["admin", "client", "worker"],
    owner: "governance",
    status: "active",
  },

  // AI OS
  {
    id: "admin-agents-global",
    labelKey: "nav.agents",
    canonicalHref: "/agents",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },
  {
    id: "admin-agents-internal",
    labelKey: "nav.agents",
    canonicalHref: "/admin/agents",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },
  {
    id: "admin-llm-metrics",
    labelKey: "nav.llmMetrics",
    canonicalHref: "/admin/llm-metrics",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },
  {
    id: "admin-agent-memory",
    labelKey: "nav.agentMemory",
    canonicalHref: "/admin/memory",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },
  {
    id: "admin-prometeo",
    labelKey: "nav.prometeo",
    canonicalHref: "/admin/prometeo",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "active",
  },

  // System OS
  {
    id: "admin-communications",
    labelKey: "nav.communications",
    canonicalHref: "/admin/communications",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-domain-events",
    labelKey: "nav.domainEvents",
    canonicalHref: "/admin/domain-events",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-users",
    labelKey: "nav.users",
    canonicalHref: "/admin/users",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-settings",
    labelKey: "nav.settings",
    canonicalHref: "/admin/settings",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-html-canvas",
    labelKey: "nav.htmlCanvas",
    canonicalHref: "/admin/html-in-canvas",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-semse-tools",
    labelKey: "nav.semseTools",
    canonicalHref: "/tools",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-algorithm-engine",
    labelKey: "nav.algorithmEngine",
    canonicalHref: "/admin/algorithm-engine",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-ecosystem",
    labelKey: "nav.ecosystem",
    canonicalHref: "/admin/ecosystem",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },
  {
    id: "admin-semse-x",
    labelKey: "nav.semseX",
    canonicalHref: "/admin/semse-x",
    layer: "workspace",
    os: "system",
    roles: ["admin"],
    owner: "platform",
    status: "active",
  },

  // Planned routes (for registry coverage / specs validation)
  {
    id: "planned-ops",
    labelKey: "nav.operations",
    canonicalHref: "/ops",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
  },
  {
    id: "planned-ops-risk",
    labelKey: "nav.risk",
    canonicalHref: "/ops/risk",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
  },
  {
    id: "planned-queue-blocked-payments",
    labelKey: "queue.blockedPayments",
    canonicalHref: "/ops/queues/blocked-payments",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
    entityType: "payment",
  },
  {
    id: "planned-queue-evidence-review",
    labelKey: "queue.evidenceReview",
    canonicalHref: "/ops/queues/evidence-review",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
    entityType: "evidence",
  },
  {
    id: "planned-queue-at-risk-jobs",
    labelKey: "queue.atRiskJobs",
    canonicalHref: "/ops/queues/at-risk-jobs",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
    entityType: "job",
  },
  {
    id: "planned-queue-client-waiting",
    labelKey: "queue.clientWaiting",
    canonicalHref: "/ops/queues/client-waiting",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
  },
  {
    id: "planned-queue-contractor-action-required",
    labelKey: "queue.contractorAction",
    canonicalHref: "/ops/queues/contractor-action-required",
    layer: "workspace",
    os: "operations",
    roles: ["admin"],
    owner: "operations",
    status: "planned",
  },
  {
    id: "planned-ai",
    labelKey: "nav.ai",
    canonicalHref: "/ai",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "planned",
  },
  {
    id: "planned-queue-ai-runtime-exceptions",
    labelKey: "queue.aiExceptions",
    canonicalHref: "/ai/queues/runtime-exceptions",
    layer: "workspace",
    os: "ai",
    roles: ["admin"],
    owner: "ai-operations",
    status: "planned",
    entityType: "trace",
  },
  {
    id: "planned-marketplace",
    labelKey: "nav.marketplace",
    canonicalHref: "/marketplace",
    layer: "workspace",
    os: "marketplace",
    roles: ["admin", "client", "worker"],
    owner: "marketplace",
    status: "planned",
  },
  {
    id: "planned-governance",
    labelKey: "nav.governance",
    canonicalHref: "/governance",
    layer: "workspace",
    os: "governance",
    roles: ["admin", "client", "worker"],
    owner: "governance",
    status: "planned",
  },
];
