import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CONSTRUCTION_LIBRARY_SEED,
  constructionLibraryItemSeedSchema,
  normalizeLibraryText,
} from "../../packages/schemas/dist/index.js";
import { buildSeedSql } from "../../packages/db/scripts/generate-construction-library-sql.mjs";

// Sense Vision — Construction Library seed integrity.
// Spec: docs/specs/vision/sense-vision-field-library.spec.md §7 / §9.

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const MIGRATION = resolve(
  root,
  "packages/db/prisma/migrations/20260924120000_sense_vision_construction_library/migration.sql",
);

test("seed has 100+ items that all satisfy the contract", () => {
  assert.ok(CONSTRUCTION_LIBRARY_SEED.length >= 100, `got ${CONSTRUCTION_LIBRARY_SEED.length}`);
  for (const item of CONSTRUCTION_LIBRARY_SEED) {
    const parsed = constructionLibraryItemSeedSchema.safeParse(item);
    assert.ok(parsed.success, `${item.slug}: ${JSON.stringify(parsed.error?.issues)}`);
  }
});

test("slugs are unique", () => {
  const slugs = CONSTRUCTION_LIBRARY_SEED.map((item) => item.slug);
  assert.equal(new Set(slugs).size, slugs.length);
});

test("no name or alias points to two different items (keeps recognition matching unambiguous)", () => {
  const owners = new Map<string, string>();
  for (const item of CONSTRUCTION_LIBRARY_SEED) {
    for (const name of [item.nameEn, item.nameEs, ...item.aliasesEn, ...item.aliasesEs]) {
      const key = normalizeLibraryText(name);
      const owner = owners.get(key);
      assert.ok(!owner || owner === item.slug, `"${name}" is used by both ${owner} and ${item.slug}`);
      owners.set(key, item.slug);
    }
  }
});

test("priority trades from the handoff are covered", () => {
  const slugs = new Set(CONSTRUCTION_LIBRARY_SEED.map((item) => item.slug));
  for (const slug of [
    "emt-coupling", "emt-connector", "compression-coupling", "compression-connector", "fish-tape", "fish-rods",
    "beam-clamp", "strut-channel", "wire-nut", "junction-box", "circuit-breaker", "receptacle", "pex-coupling",
    "ball-valve", "air-handler", "impact-driver", "drill", "tongue-and-groove-pliers",
  ]) {
    assert.ok(slugs.has(slug), slug);
  }
  const trades = new Set(CONSTRUCTION_LIBRARY_SEED.flatMap((item) => item.trades));
  for (const trade of ["electrical", "plumbing", "hvac", "general"]) assert.ok(trades.has(trade), trade);
});

test("handoff alias example resolves to one canonical item", () => {
  const pliers = CONSTRUCTION_LIBRARY_SEED.find((item) => item.slug === "tongue-and-groove-pliers");
  assert.ok(pliers);
  assert.equal(pliers.nameEs, "Pinza ajustable");
  for (const alias of ["channel locks", "Channellocks", "Water pump pliers"]) {
    assert.ok(pliers.aliasesEn.some((a) => normalizeLibraryText(a) === normalizeLibraryText(alias)), alias);
  }
  for (const alias of ["Pinza de canal", "Alicate ajustable"]) {
    assert.ok(pliers.aliasesEs.some((a) => normalizeLibraryText(a) === normalizeLibraryText(alias)), alias);
  }
});

test("items can belong to several trades (impact driver)", () => {
  const impact = CONSTRUCTION_LIBRARY_SEED.find((item) => item.slug === "impact-driver");
  assert.ok(impact && impact.trades.length >= 4);
});

test("versioned migration contains exactly the generated seed (no drift)", () => {
  const migration = readFileSync(MIGRATION, "utf8");
  const generated = buildSeedSql(CONSTRUCTION_LIBRARY_SEED);
  assert.ok(
    migration.includes(generated.trim()),
    "migration seed differs from packages/schemas/src/construction-library.seed.ts — add a NEW migration generated by packages/db/scripts/generate-construction-library-sql.mjs",
  );
  assert.match(generated, /ON CONFLICT \("slug"\) DO NOTHING;/);
});
