import type { PrometeoToolDescriptor } from "@semse/schemas";

function readTool(input: Omit<PrometeoToolDescriptor, "mode" | "riskLevel" | "approvalPolicy" | "adapterPending"> & {
  adapterPending?: boolean;
}): PrometeoToolDescriptor {
  const { adapterPending, ...rest } = input;
  return {
    ...rest,
    mode: "read",
    riskLevel: "low",
    approvalPolicy: "none",
    adapterPending: adapterPending ?? false,
  };
}

function writeTool(input: Omit<PrometeoToolDescriptor, "mode" | "riskLevel" | "approvalPolicy" | "adapterPending"> & {
  riskLevel?: PrometeoToolDescriptor["riskLevel"];
  approvalPolicy?: PrometeoToolDescriptor["approvalPolicy"];
  adapterPending?: boolean;
}): PrometeoToolDescriptor {
  const { riskLevel, approvalPolicy, adapterPending, ...rest } = input;
  return {
    ...rest,
    mode: riskLevel === "critical" ? "critical" : "write",
    riskLevel: riskLevel ?? "medium",
    approvalPolicy: approvalPolicy ?? "confirm",
    adapterPending: adapterPending ?? true,
  };
}

export const PROMETEO_TOOL_REGISTRY: PrometeoToolDescriptor[] = [
  readTool({
    namespace: "time_tracker",
    name: "get_status",
    label: "Estado del Time Tracker",
    description: "Consulta sesión activa, sesiones recientes, trabajos disponibles y resúmenes del usuario.",
    permissions: ["field-ops:read"],
    endpoint: { method: "GET", path: "/v1/time-tracker" },
    outputKind: "TrackerBootstrapView",
    tags: ["time-tracker", "field-ops", "read"],
  }),
  readTool({
    namespace: "time_tracker",
    name: "list_jobs",
    label: "Trabajos del tracker",
    description: "Lista trabajos que el usuario puede usar para registrar tiempo.",
    permissions: ["field-ops:read"],
    endpoint: { method: "GET", path: "/v1/time-tracker/jobs" },
    outputKind: "JobRecordView[]",
    tags: ["time-tracker", "jobs", "read"],
  }),
  readTool({
    namespace: "time_tracker",
    name: "get_summary",
    label: "Resumen de horas",
    description: "Consulta resumen semanal o mensual de sesiones de trabajo.",
    permissions: ["field-ops:read"],
    endpoint: { method: "GET", path: "/v1/time-tracker/summary" },
    inputSchema: { type: "object", properties: { range: { enum: ["week", "month"] } } },
    outputKind: "TrackerSummaryView",
    tags: ["time-tracker", "summary", "read"],
  }),
  readTool({
    namespace: "time_tracker",
    name: "list_sessions",
    label: "Sesiones de tiempo",
    description: "Lista sesiones de tiempo por rango, trabajo o estado.",
    permissions: ["field-ops:read"],
    endpoint: { method: "GET", path: "/v1/time-tracker/sessions" },
    inputSchema: {
      type: "object",
      properties: {
        range: { enum: ["week", "month", "all"] },
        jobId: { type: "string" },
        status: { enum: ["RUNNING", "PAUSED", "STOPPED"] },
      },
    },
    outputKind: "TrackerSessionView[]",
    tags: ["time-tracker", "sessions", "read"],
  }),
  writeTool({
    namespace: "time_tracker",
    name: "start",
    label: "Iniciar cronómetro",
    description: "Inicia una sesión de Time Tracker para un trabajo.",
    permissions: ["field-ops:write"],
    endpoint: { method: "POST", path: "/v1/time-tracker/sessions/start" },
    inputSchema: { type: "object", required: ["jobId"], properties: { jobId: { type: "string" }, notes: { type: "string" } } },
    outputKind: "TrackerSessionView",
    tags: ["time-tracker", "write"],
  }),
  writeTool({
    namespace: "time_tracker",
    name: "pause",
    label: "Pausar cronómetro",
    description: "Pausa una sesión activa de Time Tracker.",
    permissions: ["field-ops:write"],
    endpoint: { method: "POST", path: "/v1/time-tracker/sessions/:sessionId/pause" },
    inputSchema: { type: "object", required: ["sessionId"], properties: { sessionId: { type: "string" }, notes: { type: "string" } } },
    outputKind: "TrackerSessionView",
    tags: ["time-tracker", "write"],
  }),
  writeTool({
    namespace: "time_tracker",
    name: "resume",
    label: "Reanudar cronómetro",
    description: "Reanuda una sesión pausada de Time Tracker.",
    permissions: ["field-ops:write"],
    endpoint: { method: "POST", path: "/v1/time-tracker/sessions/:sessionId/resume" },
    inputSchema: { type: "object", required: ["sessionId"], properties: { sessionId: { type: "string" }, notes: { type: "string" } } },
    outputKind: "TrackerSessionView",
    tags: ["time-tracker", "write"],
  }),
  writeTool({
    namespace: "time_tracker",
    name: "stop",
    label: "Detener cronómetro",
    description: "Detiene una sesión de Time Tracker y registra notas opcionales.",
    permissions: ["field-ops:write"],
    endpoint: { method: "POST", path: "/v1/time-tracker/sessions/:sessionId/stop" },
    inputSchema: { type: "object", required: ["sessionId"], properties: { sessionId: { type: "string" }, notes: { type: "string" } } },
    outputKind: "TrackerSessionView",
    tags: ["time-tracker", "write"],
  }),
  writeTool({
    namespace: "time_tracker",
    name: "create_manual_entry",
    label: "Registro manual de tiempo",
    description: "Crea una sesión manual con fecha y horas de inicio/fin.",
    permissions: ["field-ops:write"],
    endpoint: { method: "POST", path: "/v1/time-tracker/sessions/manual" },
    inputSchema: {
      type: "object",
      required: ["jobId", "date", "startTime", "endTime"],
      properties: {
        jobId: { type: "string" },
        date: { type: "string", format: "date" },
        startTime: { type: "string" },
        endTime: { type: "string" },
        notes: { type: "string" },
      },
    },
    outputKind: "TrackerSessionView",
    tags: ["time-tracker", "write"],
  }),
  readTool({
    namespace: "vision",
    name: "get_analysis",
    label: "Análisis visual por evidencia",
    description: "Consulta el análisis visual persistido de una evidencia.",
    permissions: ["vision:read"],
    endpoint: { method: "GET", path: "/v1/vision/evidence/:evidenceId" },
    inputSchema: { type: "object", required: ["evidenceId"], properties: { evidenceId: { type: "string" } } },
    outputKind: "VisionAnalysisRecord",
    tags: ["vision", "evidence", "read"],
  }),
  readTool({
    namespace: "vision",
    name: "get_job_analyses",
    label: "Análisis visuales por trabajo",
    description: "Lista análisis visuales persistidos asociados con un trabajo.",
    permissions: ["vision:read"],
    endpoint: { method: "GET", path: "/v1/vision/job/:jobId" },
    inputSchema: { type: "object", required: ["jobId"], properties: { jobId: { type: "string" } } },
    outputKind: "VisionAnalysisRecord[]",
    tags: ["vision", "job", "evidence", "read"],
  }),
  readTool({
    namespace: "vision",
    name: "get_milestone_analyses",
    label: "Análisis visuales por hito",
    description: "Lista análisis visuales persistidos asociados con un hito.",
    permissions: ["vision:read"],
    endpoint: { method: "GET", path: "/v1/vision/milestone/:milestoneId" },
    inputSchema: { type: "object", required: ["milestoneId"], properties: { milestoneId: { type: "string" } } },
    outputKind: "VisionAnalysisRecord[]",
    tags: ["vision", "milestone", "evidence", "read"],
  }),
  readTool({
    namespace: "vision",
    name: "analyze_image",
    label: "Analizar imagen",
    description: "Ejecuta análisis visual sobre una imagen o evidencia existente.",
    permissions: ["vision:run"],
    endpoint: { method: "POST", path: "/v1/vision/analyze" },
    inputSchema: { type: "object", required: ["imageUrl"], properties: { imageUrl: { type: "string" }, jobId: { type: "string" }, milestoneId: { type: "string" } } },
    outputKind: "VisionAnalysisResult",
    tags: ["vision", "image", "evidence"],
    adapterPending: true,
  }),
  readTool({
    namespace: "vision",
    name: "compare_before_after",
    label: "Comparar antes/después",
    description: "Compara una imagen entregada contra una referencia.",
    permissions: ["vision:run"],
    endpoint: { method: "POST", path: "/v1/vision/match-reference" },
    inputSchema: { type: "object", required: ["deliveredImageUrl", "referenceImageUrl"], properties: { deliveredImageUrl: { type: "string" }, referenceImageUrl: { type: "string" } } },
    outputKind: "ReferenceMatchResult",
    tags: ["vision", "comparison", "evidence"],
    adapterPending: true,
  }),
  readTool({
    namespace: "vision",
    name: "detect_material",
    label: "Detectar material",
    description: "Detecta o valida materiales visibles en una imagen.",
    permissions: ["vision:run"],
    endpoint: { method: "POST", path: "/v1/vision/detect-material" },
    inputSchema: { type: "object", required: ["imageUrl"], properties: { imageUrl: { type: "string" }, expectedMaterial: { type: "string" } } },
    outputKind: "DetectMaterialResult",
    tags: ["vision", "materials"],
    adapterPending: true,
  }),
  readTool({
    namespace: "vision",
    name: "classify_space",
    label: "Clasificar espacio",
    description: "Clasifica el tipo de espacio visible en una imagen.",
    permissions: ["vision:run"],
    endpoint: { method: "POST", path: "/v1/vision/classify-space" },
    inputSchema: { type: "object", required: ["imageUrl"], properties: { imageUrl: { type: "string" } } },
    outputKind: "ClassifySpaceResult",
    tags: ["vision", "space"],
    adapterPending: true,
  }),
  readTool({
    namespace: "vision",
    name: "check_safety",
    label: "Revisión de seguridad",
    description: "Busca señales visuales de seguridad o EPP en una imagen.",
    permissions: ["vision:run"],
    endpoint: { method: "POST", path: "/v1/vision/safety-check-enriched" },
    inputSchema: { type: "object", required: ["imageUrl"], properties: { imageUrl: { type: "string" }, trade: { type: "string" } } },
    outputKind: "SafetyCheckResult",
    tags: ["vision", "safety"],
    adapterPending: true,
  }),
  readTool({
    namespace: "vision",
    name: "analyze_video",
    label: "Analizar video",
    description: "Tool declarada para video intelligence; requiere pipeline temporal antes de ejecución real.",
    permissions: ["vision:run"],
    inputSchema: { type: "object", required: ["videoFileId"], properties: { videoFileId: { type: "string" }, jobId: { type: "string" }, milestoneId: { type: "string" } } },
    outputKind: "VideoTimelineAnalysis",
    tags: ["vision", "video", "adapter_pending"],
    adapterPending: true,
  }),
  readTool({
    namespace: "agro",
    name: "list_farms",
    label: "Fincas disponibles",
    description: "Lista las fincas disponibles para el usuario.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms" },
    outputKind: "AgroFarm[]",
    tags: ["agro", "farm", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "get_farm",
    label: "Detalle de finca",
    description: "Consulta la ficha base de una finca.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId" },
    inputSchema: { type: "object", required: ["farmId"], properties: { farmId: { type: "string" } } },
    outputKind: "AgroFarm",
    tags: ["agro", "farm", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "get_dashboard",
    label: "Dashboard de finca",
    description: "Consulta resumen operativo de una finca.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/dashboard" },
    inputSchema: { type: "object", required: ["farmId"], properties: { farmId: { type: "string" } } },
    outputKind: "AgroFarmDashboard",
    tags: ["agro", "farm", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "list_animals",
    label: "Animales de finca",
    description: "Lista animales de una finca.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/animals" },
    inputSchema: { type: "object", required: ["farmId"], properties: { farmId: { type: "string" } } },
    outputKind: "AgroAnimal[]",
    tags: ["agro", "animals", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "get_animal",
    label: "Detalle de animal",
    description: "Consulta un animal y su contexto operativo.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/animals/:animalId" },
    inputSchema: { type: "object", required: ["animalId"], properties: { animalId: { type: "string" } } },
    outputKind: "AgroAnimal",
    tags: ["agro", "animals", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "list_groups",
    label: "Grupos de animales",
    description: "Lista grupos de animales de una finca.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/animal-groups" },
    inputSchema: { type: "object", required: ["farmId"], properties: { farmId: { type: "string" } } },
    outputKind: "AgroAnimalGroup[]",
    tags: ["agro", "groups", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "list_tasks",
    label: "Tareas de finca",
    description: "Lista tareas operativas de una finca.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/tasks" },
    inputSchema: {
      type: "object",
      required: ["farmId"],
      properties: {
        farmId: { type: "string" },
        status: { type: "string" },
        targetType: { type: "string" },
        targetId: { type: "string" },
      },
    },
    outputKind: "AgroFarmTask[]",
    tags: ["agro", "tasks", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "list_inventory",
    label: "Inventario de finca",
    description: "Lista insumos, materiales y existencias configuradas de una finca.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/inventory" },
    inputSchema: { type: "object", required: ["farmId"], properties: { farmId: { type: "string" } } },
    outputKind: "AgroInventoryItem[]",
    tags: ["agro", "inventory", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "list_costs",
    label: "Costos de finca",
    description: "Lista costos operativos de una finca con filtros opcionales por entidad.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/costs" },
    inputSchema: {
      type: "object",
      required: ["farmId"],
      properties: {
        farmId: { type: "string" },
        targetType: { type: "string" },
        targetId: { type: "string" },
      },
    },
    outputKind: "AgroCostEntry[]",
    tags: ["agro", "costs", "read"],
  }),
  readTool({
    namespace: "agro",
    name: "get_cost_summary",
    label: "Resumen de costos de finca",
    description: "Consulta resumen de costos operativos de una finca por periodo.",
    permissions: ["agro:read"],
    endpoint: { method: "GET", path: "/v1/agro/farms/:farmId/cost-summary" },
    inputSchema: {
      type: "object",
      required: ["farmId"],
      properties: {
        farmId: { type: "string" },
        days: { type: "number" },
      },
    },
    outputKind: "AgroCostSummary",
    tags: ["agro", "costs", "summary", "read"],
  }),
  writeTool({
    namespace: "agro",
    name: "create_task",
    label: "Crear tarea agro",
    description: "Crea una tarea operativa de finca con confirmación del usuario.",
    permissions: ["agro:write"],
    endpoint: { method: "POST", path: "/v1/agro/farms/:farmId/tasks" },
    inputSchema: {
      type: "object",
      required: ["farmId", "title", "type"],
      properties: {
        farmId: { type: "string" },
        title: { type: "string" },
        type: { enum: ["FEEDING", "VACCINATION", "TREATMENT", "WEIGHING", "MOVEMENT", "CLEANING", "INSPECTION", "INVENTORY", "SALE", "WATER_CHECK", "OTHER"] },
        priority: { enum: ["LOW", "MEDIUM", "HIGH", "URGENT"] },
      },
    },
    outputKind: "AgroFarmTask",
    tags: ["agro", "tasks", "write"],
  }),
  writeTool({
    namespace: "payments",
    name: "propose_release",
    label: "Proponer liberación de pago",
    description: "Prepara una propuesta de liberación; la ejecución financiera exige aprobación humana.",
    // "payments:write" does not exist in packages/auth/src/rbac.ts — no role
    // ever granted it, so this tool was unreachable by anyone. The real
    // release endpoint (PaymentsController.release) already gates on
    // "projects:financials:write" (CLIENT, OPS_ADMIN); reuse that instead of
    // inventing a new permission.
    permissions: ["projects:financials:write"],
    endpoint: { method: "POST", path: "/v1/milestones/:milestoneId/escrow/release" },
    inputSchema: { type: "object", required: ["milestoneId"], properties: { milestoneId: { type: "string" }, amount: { type: "number" } } },
    outputKind: "EscrowView",
    tags: ["payments", "escrow", "critical"],
    riskLevel: "critical",
    approvalPolicy: "human_required",
  }),
  readTool({
    namespace: "materials",
    name: "calculate",
    label: "Calcular materiales",
    description: "Calcula cantidades de materiales de construcción (pintura, drywall, pisos, concreto, madera, mulch) usando las fórmulas del skill materiales-obra.",
    permissions: ["tools:run"],
    endpoint: { method: "POST", path: "/v1/tools/materials" },
    inputSchema: {
      type: "object",
      required: ["category", "lengthFt", "widthFt"],
      properties: {
        category: { enum: ["painting", "drywall", "flooring", "concrete", "lumber", "mulch"] },
        lengthFt: { type: "number" },
        widthFt: { type: "number" },
        heightFt: { type: "number" },
        depthInches: { type: "number" },
        doors: { type: "number" },
        windows: { type: "number" },
        coats: { type: "number" },
        installation: { enum: ["straight", "diagonal", "irregular"] },
        corners: { type: "number" },
        openings: { type: "number" },
        includeCeiling: { type: "boolean" },
      },
    },
    outputKind: "MaterialsEstimate",
    tags: ["tools", "materials", "read"],
  }),
];

export function listPrometeoToolRegistry(): PrometeoToolDescriptor[] {
  return PROMETEO_TOOL_REGISTRY;
}

export function findPrometeoToolDescriptor(namespace: string, name: string): PrometeoToolDescriptor | undefined {
  return PROMETEO_TOOL_REGISTRY.find((tool) => tool.namespace === namespace && tool.name === name);
}
