import type { ForgeAgentManifest, ForgeAgentRole } from "./types.js";

const commonAudit = ["audit.record"] as const;

export const forgeAgentRegistry: Record<ForgeAgentRole, ForgeAgentManifest> = {
  "forge-supervisor": {
    id: "forge-supervisor-v1",
    role: "forge-supervisor",
    name: "SEMSE Forge Supervisor",
    version: "1.0.0",
    status: "preview",
    description: "Coordinates the engineering run, delegates bounded tasks and requests approvals.",
    owner: "semse-core",
    allowedTools: ["repo.read", "repo.search", "spec.read", "task.plan", "pr.prepare", "approval.request", ...commonAudit],
    allowedActions: ["run.coordinate", "task.assign", "review.request", "pr.prepare"],
    fileScopes: ["docs/specs/**", ".semse-sdd/**", "packages/**", "apps/**", "tests/**", "scripts/**"],
    networkScopes: ["github.com/Semse-projet/project-manager-app"],
    maxRiskLevel: "critical",
    approvalMode: "ops_admin",
    modelClass: "reasoning",
    tags: ["orchestration", "sdd", "control-plane"]
  },
  "spec-architect": {
    id: "spec-architect-v1",
    role: "spec-architect",
    name: "Spec Architect",
    version: "1.0.0",
    status: "active",
    description: "Converts approved intent into canonical SEMSE specs and acceptance criteria.",
    owner: "semse-architecture",
    allowedTools: ["repo.read", "repo.search", "spec.read", "spec.write", "task.plan", ...commonAudit],
    allowedActions: ["spec.draft", "spec.refine", "acceptance.define", "dependency.map"],
    fileScopes: ["docs/specs/**", ".semse-sdd/**", "docs/adr/**"],
    networkScopes: [],
    maxRiskLevel: "high",
    approvalMode: "ops_admin",
    modelClass: "reasoning",
    tags: ["spec", "architecture", "requirements"]
  },
  "domain-architect": {
    id: "domain-architect-v1",
    role: "domain-architect",
    name: "Domain Architect",
    version: "1.0.0",
    status: "active",
    description: "Maps domain boundaries, entities, events and contracts without crossing authority boundaries.",
    owner: "semse-architecture",
    allowedTools: ["repo.read", "repo.search", "spec.read", "spec.write", "schema.propose", "task.plan", ...commonAudit],
    allowedActions: ["domain.map", "contract.propose", "event.map", "schema.propose"],
    fileScopes: ["docs/specs/**", "docs/foundation/**", "packages/schemas/**", "packages/shared/**"],
    networkScopes: [],
    maxRiskLevel: "high",
    approvalMode: "ops_admin",
    modelClass: "reasoning",
    tags: ["ddd", "contracts", "events"]
  },
  "creator-mentor": {
    id: "creator-mentor-v1",
    role: "creator-mentor",
    name: "Creator Mentor",
    version: "1.0.0",
    status: "active",
    description: "Extracts a professor or expert's knowledge and converts it into an app blueprint.",
    owner: "semse-creator",
    allowedTools: ["spec.read", "spec.write", "task.plan", "marketplace.publish.propose", ...commonAudit],
    allowedActions: ["creator.interview", "blueprint.create", "curriculum.structure", "publication.propose"],
    fileScopes: ["docs/specs/creator/**", ".semse-sdd/forge/creator/**", "packages/forge/**"],
    networkScopes: [],
    maxRiskLevel: "high",
    approvalMode: "creator_review",
    modelClass: "reasoning",
    tags: ["creator", "education", "knowledge-extraction"]
  },
  "ux-composer": {
    id: "ux-composer-v1",
    role: "ux-composer",
    name: "UX Composer",
    version: "1.0.0",
    status: "preview",
    description: "Produces accessible interaction flows and bounded UI changes from approved specs.",
    owner: "semse-web",
    allowedTools: ["repo.read", "repo.search", "spec.read", "code.write", "test.write", ...commonAudit],
    allowedActions: ["ux.flow", "ui.compose", "accessibility.verify"],
    fileScopes: ["apps/web/**", "packages/ui/**", "tests/e2e-semse/**", "docs/specs/ui/**"],
    networkScopes: [],
    maxRiskLevel: "medium",
    approvalMode: "none",
    modelClass: "vision",
    tags: ["ux", "ui", "accessibility"]
  },
  "data-engineer": {
    id: "data-engineer-v1",
    role: "data-engineer",
    name: "Data Engineer",
    version: "1.0.0",
    status: "preview",
    description: "Proposes schemas, migrations and data contracts with mandatory rollback.",
    owner: "semse-data",
    allowedTools: ["repo.read", "repo.search", "spec.read", "schema.propose", "migration.propose", "test.write", ...commonAudit],
    allowedActions: ["schema.propose", "migration.propose", "data.contract", "rollback.plan"],
    fileScopes: ["packages/db/**", "packages/schemas/**", "docs/specs/**", "tests/**"],
    networkScopes: [],
    maxRiskLevel: "critical",
    approvalMode: "dual_control",
    modelClass: "coding",
    tags: ["database", "prisma", "migration"]
  },
  "backend-builder": {
    id: "backend-builder-v1",
    role: "backend-builder",
    name: "Backend Builder",
    version: "1.0.0",
    status: "preview",
    description: "Implements approved NestJS, worker and package changes within explicit file scopes.",
    owner: "semse-api",
    allowedTools: ["repo.read", "repo.search", "spec.read", "code.write", "test.write", "command.run", ...commonAudit],
    allowedActions: ["code.implement", "test.implement", "api.contract.implement"],
    fileScopes: ["apps/api/**", "apps/worker/**", "packages/**", "tests/**"],
    networkScopes: [],
    maxRiskLevel: "high",
    approvalMode: "none",
    modelClass: "coding",
    tags: ["backend", "nestjs", "worker"]
  },
  "frontend-builder": {
    id: "frontend-builder-v1",
    role: "frontend-builder",
    name: "Frontend Builder",
    version: "1.0.0",
    status: "preview",
    description: "Implements approved Next.js and shared UI changes.",
    owner: "semse-web",
    allowedTools: ["repo.read", "repo.search", "spec.read", "code.write", "test.write", "command.run", ...commonAudit],
    allowedActions: ["code.implement", "test.implement", "ui.implement"],
    fileScopes: ["apps/web/**", "packages/ui/**", "packages/shared/**", "tests/e2e-semse/**"],
    networkScopes: [],
    maxRiskLevel: "high",
    approvalMode: "none",
    modelClass: "coding",
    tags: ["frontend", "nextjs", "ui"]
  },
  "integration-engineer": {
    id: "integration-engineer-v1",
    role: "integration-engineer",
    name: "Integration Engineer",
    version: "1.0.0",
    status: "preview",
    description: "Builds governed connectors and validates external contracts.",
    owner: "semse-platform",
    allowedTools: ["repo.read", "repo.search", "spec.read", "code.write", "test.write", "command.run", "approval.request", ...commonAudit],
    allowedActions: ["connector.implement", "contract.verify", "webhook.verify"],
    fileScopes: ["apps/api/**", "packages/**", "docs/specs/integrations/**", "tests/**"],
    networkScopes: ["approved-connectors-only"],
    maxRiskLevel: "high",
    approvalMode: "security",
    modelClass: "coding",
    tags: ["integration", "connector", "webhook"]
  },
  "qa-verifier": {
    id: "qa-verifier-v1",
    role: "qa-verifier",
    name: "QA Verifier",
    version: "1.0.0",
    status: "active",
    description: "Runs the verification matrix and reports evidence without changing implementation.",
    owner: "semse-quality",
    allowedTools: ["repo.read", "spec.read", "test.write", "command.run", ...commonAudit],
    allowedActions: ["verify.typecheck", "verify.lint", "verify.test", "verify.build", "verify.acceptance"],
    fileScopes: ["tests/**", "docs/reportes/**", ".semse-sdd/**"],
    networkScopes: [],
    maxRiskLevel: "medium",
    approvalMode: "none",
    modelClass: "coding",
    tags: ["qa", "verification", "evidence"]
  },
  "security-reviewer": {
    id: "security-reviewer-v1",
    role: "security-reviewer",
    name: "Security Reviewer",
    version: "1.0.0",
    status: "active",
    description: "Reviews authorization, secrets, dependencies and threat boundaries.",
    owner: "semse-security",
    allowedTools: ["repo.read", "repo.search", "spec.read", "test.write", "command.run", "approval.request", ...commonAudit],
    allowedActions: ["security.review", "threat.model", "dependency.audit", "approval.request"],
    fileScopes: ["apps/**", "packages/**", "docs/specs/**", "docs/reportes/**", ".github/**"],
    networkScopes: [],
    maxRiskLevel: "critical",
    approvalMode: "security",
    modelClass: "reasoning",
    tags: ["security", "threat-model", "authorization"]
  },
  "devops-release": {
    id: "devops-release-v1",
    role: "devops-release",
    name: "DevOps Release",
    version: "1.0.0",
    status: "preview",
    description: "Prepares CI and deployment proposals; never performs unapproved production mutation.",
    owner: "semse-platform",
    allowedTools: ["repo.read", "repo.search", "spec.read", "code.write", "test.write", "command.run", "deployment.propose", "approval.request", ...commonAudit],
    allowedActions: ["ci.implement", "deployment.propose", "rollback.prepare"],
    fileScopes: [".github/**", "infra/**", "Dockerfile*", "railway.json", "scripts/**", "docs/runbooks/**"],
    networkScopes: ["railway.app", "github.com"],
    maxRiskLevel: "critical",
    approvalMode: "dual_control",
    modelClass: "coding",
    tags: ["devops", "ci", "release"]
  },
  "documentation-curator": {
    id: "documentation-curator-v1",
    role: "documentation-curator",
    name: "Documentation Curator",
    version: "1.0.0",
    status: "active",
    description: "Keeps specs, ADRs, runbooks and changelogs aligned with verified implementation.",
    owner: "semse-docs",
    allowedTools: ["repo.read", "repo.search", "spec.read", "spec.write", ...commonAudit],
    allowedActions: ["docs.update", "changelog.update", "runbook.update", "traceability.update"],
    fileScopes: ["docs/**", ".semse-sdd/**", "README.md", "CHANGELOG.md"],
    networkScopes: [],
    maxRiskLevel: "medium",
    approvalMode: "none",
    modelClass: "lightweight",
    tags: ["documentation", "traceability", "knowledge"]
  },
  "governance-auditor": {
    id: "governance-auditor-v1",
    role: "governance-auditor",
    name: "Governance Auditor",
    version: "1.0.0",
    status: "active",
    description: "Checks authority boundaries, approvals, policy compliance and audit completeness.",
    owner: "semse-governance",
    allowedTools: ["repo.read", "repo.search", "spec.read", "command.run", "approval.request", ...commonAudit],
    allowedActions: ["governance.review", "authority.verify", "audit.verify", "approval.request"],
    fileScopes: ["docs/constitution/**", "docs/specs/**", "packages/agents/**", "packages/forge/**", "docs/reportes/**"],
    networkScopes: [],
    maxRiskLevel: "critical",
    approvalMode: "dual_control",
    modelClass: "reasoning",
    tags: ["governance", "authority", "audit"]
  }
};

export function getForgeAgentManifest(role: ForgeAgentRole): ForgeAgentManifest {
  return forgeAgentRegistry[role];
}

export function listForgeAgentManifests(): ForgeAgentManifest[] {
  return Object.values(forgeAgentRegistry);
}
