import { basename, normalize, posix } from "node:path";
import type { AutonomyTaskPlan } from "./types.js";
import { sanitizeBranchName } from "./validator.js";

function trimToUndefined(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

function resolveLlmConfig(input: {
  llmApiKey?: string;
  llmModel?: string;
  llmBaseUrl?: string;
  openAiApiKey?: string;
  openAiModel?: string;
  openAiBaseUrl?: string;
}): { apiKey?: string; model?: string; baseUrl?: string } {
  return {
    apiKey: trimToUndefined(input.llmApiKey) ?? trimToUndefined(input.openAiApiKey),
    model: trimToUndefined(input.llmModel) ?? trimToUndefined(input.openAiModel),
    baseUrl: trimToUndefined(input.llmBaseUrl) ?? trimToUndefined(input.openAiBaseUrl)
  };
}

function isLocalCompatibleEndpoint(baseUrl: string | undefined): boolean {
  if (!baseUrl) return false;
  try {
    const parsed = new URL(baseUrl);
    return ["127.0.0.1", "localhost", "::1"].includes(parsed.hostname);
  } catch {
    return false;
  }
}

function extractJson(text: string): string {
  const codeFence = text.match(/```json\s*([\s\S]+?)```/i);
  if (codeFence) return codeFence[1]!.trim();

  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    return text.slice(firstBrace, lastBrace + 1).trim();
  }
  return text.trim();
}

/**
 * Sanitize a file path coming from the LLM:
 * - Must be relative (no leading slash)
 * - No path traversal (..)
 * - Falls back to generated/ if invalid
 */
function sanitizeFilePath(raw: string | undefined, fallbackSlug: string): string {
  if (!raw || typeof raw !== "string") return `generated/${fallbackSlug}`;
  const normalized = posix.normalize(raw.trim().replace(/\\/g, "/"));
  if (normalized.startsWith("..") || normalized.startsWith("/")) {
    return `generated/${fallbackSlug}`;
  }
  return normalized;
}

function fallbackPlan(task: string): AutonomyTaskPlan {
  const branchName = sanitizeBranchName(task);
  const slug = branchName.replace(/^feat\//, "");
  const filePath = `generated/${slug}.md`;
  return {
    task,
    branchName,
    filePath,
    content: `# Autonomous Change\n\n- task: ${task}\n- generatedAt: ${new Date().toISOString()}\n- mode: fallback\n`,
    commitMessage: `feat: ${task}`,
    prTitle: `feat: ${task}`,
    prBody: `## Summary\n\n${task}\n\n## Notes\n\nGenerated by SEMSE autonomy.`,
    summary: `Generated ${basename(filePath)} for task "${task}"`
  };
}

const SYSTEM_PROMPT = `You are an autonomous software engineer. When given a task, you produce a JSON plan to implement it as a real code change in a repository.

Return exactly one JSON object with these keys:
- branchName: string starting with feat/, fix/, or chore/
- filePath: string — relative path from repo root to the file to create or modify (e.g. "src/utils/format.ts", "scripts/seed.mjs"). Real source files, not under generated/.
- content: string — the complete file content. Must be real, working code appropriate for the file extension. No markdown fences in content.
- commitMessage: string — conventional commit message (feat/fix/chore: description)
- prTitle: string — short PR title under 72 chars
- prBody: string — markdown PR description with ## Summary and ## Changes sections
- summary: string — one sentence summary

Rules:
- Write real, complete code — not pseudocode or placeholder text
- Choose the file extension based on the task (e.g. .ts for TypeScript, .py for Python, .mjs for ESM scripts, .md for docs)
- The code must be self-contained and syntactically correct
- No markdown fences in the content field
- No explanations outside the JSON`;

export async function generateTaskPlan(input: {
  task: string;
  llmApiKey?: string;
  llmModel?: string;
  llmBaseUrl?: string;
  openAiApiKey?: string;
  openAiModel?: string;
  openAiBaseUrl?: string;
}): Promise<AutonomyTaskPlan> {
  const llm = resolveLlmConfig(input);
  const localCompatible = isLocalCompatibleEndpoint(llm.baseUrl);
  const canCallModel = Boolean(llm.apiKey || localCompatible);

  if (!canCallModel) {
    return fallbackPlan(input.task);
  }

  const branchSlug = sanitizeBranchName(input.task).replace(/^feat\//, "");

  try {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (llm.apiKey) {
      headers.authorization = `Bearer ${llm.apiKey}`;
    }

    const body: Record<string, unknown> = {
      model: llm.model ?? "qwen2.5:3b",
      temperature: 0.1,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: `Task: ${input.task}` }
      ]
    };

    if (!localCompatible) {
      body.response_format = { type: "json_object" };
    }

    const response = await fetch(`${llm.baseUrl ?? "https://api.openai.com/v1"}/chat/completions`, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(localCompatible ? 180000 : 60000)
    });

    if (!response.ok) return fallbackPlan(input.task);

    const data = (await response.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const rawContent = data.choices?.[0]?.message?.content;
    if (!rawContent) return fallbackPlan(input.task);

    const parsed = JSON.parse(extractJson(rawContent)) as Partial<AutonomyTaskPlan>;

    const fb = fallbackPlan(input.task);
    return {
      task: input.task,
      branchName: parsed.branchName || fb.branchName,
      filePath: sanitizeFilePath(parsed.filePath, `${branchSlug}.md`),
      content: parsed.content || fb.content,
      commitMessage: parsed.commitMessage || `feat: ${input.task}`,
      prTitle: parsed.prTitle || `feat: ${input.task}`,
      prBody: parsed.prBody || `## Summary\n\n${input.task}`,
      summary: parsed.summary || input.task
    };
  } catch {
    return fallbackPlan(input.task);
  }
}
