import type { IntakeQuestion } from "../../smart-intake.types.js";

export const CLEANING_QUESTIONS: IntakeQuestion[] = [
  {
    id: "cleaning_type",
    category: "cleaning",
    step: 1,
    label: {
      es: "¿Qué tipo de limpieza necesita?",
      en: "What type of cleaning is needed?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: true,
    allowNotSure: true,
    options: [
      { label: { es: "Limpieza estándar / mantenimiento", en: "Standard / maintenance cleaning" }, value: "standard" },
      { label: { es: "Limpieza profunda", en: "Deep cleaning" }, value: "deep" },
      { label: { es: "Limpieza después de mudanza", en: "Move-in / move-out cleaning" }, value: "move_inout" },
      { label: { es: "Limpieza post-construcción", en: "Post-construction cleaning" }, value: "post_construction" },
      { label: { es: "Limpieza comercial u oficina", en: "Commercial or office cleaning" }, value: "commercial" },
    ],
  },
  {
    id: "cleaning_size",
    category: "cleaning",
    step: 2,
    label: {
      es: "¿Cuál es el tamaño aproximado del espacio a limpiar?",
      en: "What is the approximate size of the space to be cleaned?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "Menos de 500 sq ft (estudio o 1 cuarto)", en: "Under 500 sq ft (studio or 1 room)" }, value: "under_500" },
      { label: { es: "500 – 1,000 sq ft (1–2 habitaciones)", en: "500 – 1,000 sq ft (1–2 bedrooms)" }, value: "500_1000" },
      { label: { es: "1,000 – 2,000 sq ft (3–4 habitaciones)", en: "1,000 – 2,000 sq ft (3–4 bedrooms)" }, value: "1000_2000" },
      { label: { es: "Más de 2,000 sq ft", en: "Over 2,000 sq ft" }, value: "over_2000" },
    ],
  },
  {
    id: "cleaning_frequency",
    category: "cleaning",
    step: 3,
    label: {
      es: "¿Qué tan seguido necesita el servicio?",
      en: "How often is the service needed?",
    },
    required: false,
    affectsEstimate: false,
    estimateImpact: "low",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "Una sola vez", en: "One time only" }, value: "one_time" },
      { label: { es: "Semanal", en: "Weekly" }, value: "weekly" },
      { label: { es: "Quincenal", en: "Bi-weekly" }, value: "biweekly" },
      { label: { es: "Mensual", en: "Monthly" }, value: "monthly" },
    ],
  },
  {
    id: "cleaning_extras",
    category: "cleaning",
    step: 4,
    label: {
      es: "¿Incluye alguno de estos servicios adicionales?",
      en: "Does it include any of these additional services?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "medium",
    answerType: "single_choice",
    allowOther: true,
    allowNotSure: true,
    options: [
      { label: { es: "No — solo limpieza estándar", en: "No — standard cleaning only" }, value: "none" },
      { label: { es: "Limpieza de ventanas", en: "Window cleaning" }, value: "windows" },
      { label: { es: "Limpieza de alfombras", en: "Carpet cleaning" }, value: "carpet" },
      { label: { es: "Desinfección o sanitización profunda", en: "Disinfection or deep sanitizing" }, value: "disinfection" },
    ],
  },
];
