import type { IntakeQuestion } from "../../smart-intake.types.js";

export const EXTERIOR_PAINTING_QUESTIONS: IntakeQuestion[] = [
  {
    id: "ext_painting_surface",
    category: "exterior_painting",
    step: 1,
    label: {
      es: "¿Qué superficie exterior se va a pintar?",
      en: "Which exterior surface will be painted?",
    },
    description: {
      es: "El tipo de superficie afecta la preparación y el costo del material.",
      en: "Surface type affects prep work and material cost.",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: true,
    allowNotSure: true,
    options: [
      { label: { es: "Paredes / siding", en: "Walls / siding" }, value: "siding" },
      { label: { es: "Madera / trim", en: "Wood / trim" }, value: "wood_trim" },
      { label: { es: "Estuco", en: "Stucco" }, value: "stucco" },
      { label: { es: "Bloque o concreto", en: "Block or concrete" }, value: "concrete" },
      { label: { es: "Todo lo anterior", en: "All of the above" }, value: "full_exterior" },
    ],
  },
  {
    id: "ext_painting_area",
    category: "exterior_painting",
    step: 2,
    label: {
      es: "¿Cuál es el área aproximada a pintar?",
      en: "What is the approximate area to be painted?",
    },
    description: {
      es: "Incluye todas las paredes exteriores del proyecto.",
      en: "Include all exterior walls of the project.",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: true,
    allowNotSure: true,
    options: [
      { label: { es: "Menos de 500 sq ft", en: "Under 500 sq ft" }, value: "under_500_sqft" },
      { label: { es: "500 – 1,000 sq ft", en: "500 – 1,000 sq ft" }, value: "500_1000_sqft" },
      { label: { es: "1,000 – 2,000 sq ft", en: "1,000 – 2,000 sq ft" }, value: "1000_2000_sqft" },
      { label: { es: "Más de 2,000 sq ft", en: "Over 2,000 sq ft" }, value: "over_2000_sqft" },
    ],
  },
  {
    id: "ext_painting_condition",
    category: "exterior_painting",
    step: 3,
    label: {
      es: "¿En qué condición está la superficie actual?",
      en: "What is the current condition of the surface?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: true,
    allowNotSure: true,
    options: [
      { label: { es: "Buena — solo limpieza leve", en: "Good — light cleaning only" }, value: "good" },
      { label: { es: "Pintura descascarada o grietas menores", en: "Peeling paint or minor cracks" }, value: "peeling" },
      { label: { es: "Daño por humedad o moho", en: "Moisture or mold damage" }, value: "moisture_mold" },
      { label: { es: "Madera podrida o daño estructural", en: "Rotted wood or structural damage" }, value: "structural_damage" },
    ],
    warningIfSelected: {
      optionValue: "structural_damage",
      warningId: "warning_structural_damage",
    },
  },
  {
    id: "ext_painting_coats",
    category: "exterior_painting",
    step: 4,
    label: {
      es: "¿Cuántas manos de pintura se necesitan?",
      en: "How many coats of paint are needed?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "medium",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "1 mano", en: "1 coat" }, value: "1" },
      { label: { es: "2 manos (recomendado)", en: "2 coats (recommended)" }, value: "2" },
      { label: { es: "3 manos o más", en: "3 coats or more" }, value: "3_plus" },
    ],
  },
  {
    id: "ext_painting_access",
    category: "exterior_painting",
    step: 5,
    label: {
      es: "¿Se necesitan escaleras o andamios para acceder al área?",
      en: "Are ladders or scaffolding needed to reach the area?",
    },
    description: {
      es: "El acceso en altura aumenta el costo y el tiempo de trabajo.",
      en: "Elevated access increases cost and labor time.",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "medium",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "No — todo accesible desde el suelo", en: "No — all ground-level accessible" }, value: "no" },
      { label: { es: "Sí — escalera estándar", en: "Yes — standard ladder" }, value: "ladder" },
      { label: { es: "Sí — andamios necesarios (2+ pisos)", en: "Yes — scaffolding needed (2+ stories)" }, value: "scaffolding" },
    ],
  },
];
