import type { IntakeQuestion } from "../../smart-intake.types.js";

export const KITCHEN_QUESTIONS: IntakeQuestion[] = [
  {
    id: "kitchen_scope",
    category: "kitchen_remodel",
    step: 1,
    label: {
      es: "¿Qué tipo de trabajo necesita la cocina?",
      en: "What type of kitchen work is needed?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: true,
    allowNotSure: true,
    options: [
      { label: { es: "Pintura y actualización de gabinetes", en: "Cabinet paint and update" }, value: "cabinet_update" },
      { label: { es: "Reemplazo de mesadas / encimeras", en: "Countertop replacement" }, value: "countertops" },
      { label: { es: "Nuevo piso o azulejos", en: "New floor or tile" }, value: "flooring" },
      { label: { es: "Renovación completa de cocina", en: "Full kitchen renovation" }, value: "full_remodel" },
    ],
  },
  {
    id: "kitchen_size",
    category: "kitchen_remodel",
    step: 2,
    label: {
      es: "¿Cuál es el tamaño aproximado de la cocina?",
      en: "What is the approximate size of the kitchen?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "Pequeña — menos de 100 sq ft", en: "Small — under 100 sq ft" }, value: "small" },
      { label: { es: "Mediana — 100 – 200 sq ft", en: "Medium — 100 – 200 sq ft" }, value: "medium" },
      { label: { es: "Grande — 200 – 350 sq ft", en: "Large — 200 – 350 sq ft" }, value: "large" },
      { label: { es: "Muy grande — más de 350 sq ft", en: "Extra large — over 350 sq ft" }, value: "extra_large" },
    ],
  },
  {
    id: "kitchen_appliances",
    category: "kitchen_remodel",
    step: 3,
    label: {
      es: "¿Se incluyen electrodomésticos en el proyecto?",
      en: "Are appliances included in the project?",
    },
    description: {
      es: "Los electrodomésticos pueden representar el 30–50% del presupuesto total.",
      en: "Appliances can represent 30–50% of the total budget.",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "No — solo mano de obra y materiales de construcción", en: "No — labor and construction materials only" }, value: "no_appliances" },
      { label: { es: "Sí — electrodomésticos básicos", en: "Yes — basic appliances" }, value: "basic_appliances" },
      { label: { es: "Sí — electrodomésticos de alta gama", en: "Yes — high-end appliances" }, value: "premium_appliances" },
    ],
  },
  {
    id: "kitchen_materials",
    category: "kitchen_remodel",
    step: 4,
    label: {
      es: "¿Qué nivel de materiales prefiere para gabinetes y mesadas?",
      en: "What material quality level do you prefer for cabinets and countertops?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "high",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "Económico — laminado / melamina", en: "Budget — laminate / melamine" }, value: "budget" },
      { label: { es: "Estándar — madera o granito básico", en: "Standard — wood or basic granite" }, value: "standard" },
      { label: { es: "Premium — cuarzo, madera sólida", en: "Premium — quartz, solid wood" }, value: "premium" },
    ],
  },
  {
    id: "kitchen_plumbing",
    category: "kitchen_remodel",
    step: 5,
    label: {
      es: "¿Se necesita mover o ampliar la plomería o el cableado eléctrico?",
      en: "Does the plumbing or electrical wiring need to be moved or extended?",
    },
    required: false,
    affectsEstimate: true,
    estimateImpact: "medium",
    answerType: "single_choice",
    allowOther: false,
    allowNotSure: true,
    options: [
      { label: { es: "No — mismas ubicaciones", en: "No — same locations" }, value: "no" },
      { label: { es: "Solo cambios menores", en: "Minor changes only" }, value: "minor" },
      { label: { es: "Sí — reubicar plomería o eléctrica", en: "Yes — relocate plumbing or electrical" }, value: "relocate" },
    ],
    warningIfSelected: {
      optionValue: "relocate",
      warningId: "warning_plumbing_relocation",
    },
  },
];
